"""Semantic witness rendering for ALTER FOREIGN TABLE factor-loop cases."""

from __future__ import annotations

from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path
from typing import Mapping

import yaml

from .alter_foreign_table_factor_loop import AlterForeignTableFactorCase
from .alter_foreign_table_regress import load_alter_foreign_table_type_witnesses


_COLUMN_STRUCTURE_CATALOG = Path(
    "skills/pg-sql-generation/references/common/"
    "pg18_column_structure_catalog.yaml"
)


class AlterForeignTableFactorRenderError(ValueError):
    """Raised when a factor value has no exact executable renderer."""


@dataclass(frozen=True)
class AlterForeignTableFactorWitness:
    primary_obligation_id: str
    setup_sql: tuple[str, ...]
    target_sql_fragment: str
    oracle_sql: tuple[str, ...]
    cleanup_sql: tuple[str, ...]
    semantic_locus: str
    outcome: str
    expected_sqlstate: str


COLLATION_SQL = {
    "omitted_type_default": "",
    "explicit_database_default": 'COLLATE pg_catalog."default"',
    "explicit_builtin_c": 'COLLATE pg_catalog."C"',
    "explicit_builtin_posix": 'COLLATE pg_catalog."POSIX"',
    "explicit_user_defined_collation": "COLLATE {prefix}collation",
    "quoted_collation_name": 'COLLATE "{prefix}Mixed Collation"',
    "schema_qualified_collation_name": (
        "COLLATE {prefix}collation_schema.{prefix}collation"
    ),
    "nonexistent_collation": "COLLATE {prefix}missing_collation",
    "collation_on_noncollatable_type": 'COLLATE pg_catalog."C"',
    "encoding_incompatible_collation": "COLLATE {prefix}encoding_collation",
}

NULLABILITY_SQL = {
    "implicit_nullable": "",
    "explicit_null": "NULL",
    "unnamed_not_null": "NOT NULL",
    "named_not_null": 'CONSTRAINT "nn factor" NOT NULL',
    "not_null_no_inherit": "NOT NULL NO INHERIT",
    "not_null_enforced": "NOT NULL ENFORCED",
    "not_null_not_enforced": "NOT NULL NOT ENFORCED",
    "duplicate_not_null_declarations": "NOT NULL NOT NULL",
    "explicit_null_with_not_null": "NULL NOT NULL",
}

DEFAULT_SQL = {
    "no_default": "",
    "explicit_default_null": "DEFAULT NULL",
    "type_literal_default": "DEFAULT 7",
    "immutable_expression_default": "DEFAULT (2 + 3)",
    "stable_expression_default": "DEFAULT CURRENT_DATE",
    "volatile_expression_default": "DEFAULT random()",
    "sequence_nextval_dependency": "DEFAULT nextval('{prefix}default_seq')",
    "user_function_dependency": "DEFAULT {prefix}default_fn()",
    "assignment_cast_compatible_default": "DEFAULT 7::smallint",
    "incompatible_type_default": "DEFAULT 'not-an-integer'",
    "self_column_reference_default": "DEFAULT {column_name}",
    "other_column_reference_default": "DEFAULT {other_column_name}",
    "subquery_default": "DEFAULT (SELECT 1)",
}

GENERATION_SQL = {
    "ordinary_base_column": "",
    "generated_virtual_default_spelling": "GENERATED ALWAYS AS (7)",
    "generated_virtual_explicit": "GENERATED ALWAYS AS (7) VIRTUAL",
    "generated_stored": "GENERATED ALWAYS AS (7) STORED",
    "immutable_same_type_expression": "GENERATED ALWAYS AS (2 + 3) STORED",
    "immutable_coercible_expression": (
        "GENERATED ALWAYS AS ('7'::smallint) STORED"
    ),
    "volatile_generation_expression": "GENERATED ALWAYS AS (random()) STORED",
    "stable_generation_expression": (
        "GENERATED ALWAYS AS (EXTRACT(DAY FROM CURRENT_DATE)) STORED"
    ),
    "self_reference_generation_expression": (
        "GENERATED ALWAYS AS ({column_name} + 1) STORED"
    ),
    "generated_column_reference": (
        "GENERATED ALWAYS AS ({prefix}generated_col + 1) STORED"
    ),
    "subquery_generation_expression": (
        "GENERATED ALWAYS AS ((SELECT 1)) STORED"
    ),
    "incompatible_generation_result_type": (
        "GENERATED ALWAYS AS ('text') STORED"
    ),
}

IDENTITY_SQL = {
    "no_identity": "",
    "generated_always_identity": "GENERATED ALWAYS AS IDENTITY",
    "generated_by_default_identity": "GENERATED BY DEFAULT AS IDENTITY",
    "generated_always_identity_with_sequence_options": (
        "GENERATED ALWAYS AS IDENTITY (START WITH 11 INCREMENT BY 3)"
    ),
    "generated_by_default_identity_with_sequence_options": (
        "GENERATED BY DEFAULT AS IDENTITY (START WITH 13 INCREMENT BY 5)"
    ),
    "identity_on_non_integer_type": "GENERATED ALWAYS AS IDENTITY",
}

STORAGE_COMPRESSION_SQL = {
    "storage_default": "STORAGE DEFAULT",
    "storage_plain": "STORAGE PLAIN",
    "storage_main": "STORAGE MAIN",
    "storage_extended": "STORAGE EXTENDED",
    "storage_external": "STORAGE EXTERNAL",
    "compression_omitted": "",
    "compression_default": "COMPRESSION DEFAULT",
    "compression_pglz": "COMPRESSION pglz",
    "compression_lz4": "COMPRESSION lz4",
    "unknown_compression_method": "COMPRESSION missing_compressor",
    "incompatible_fixed_length_storage_mode": "STORAGE EXTERNAL",
}


def direct_member_renderer_registry() -> dict[str, dict[str, str]]:
    """Return a mutable copy so mutation tests cannot alter module constants."""

    return {
        "collation": dict(COLLATION_SQL),
        "nullability": dict(NULLABILITY_SQL),
        "default_state": dict(DEFAULT_SQL),
        "generation_mode": dict(GENERATION_SQL),
        "identity_mode": dict(IDENTITY_SQL),
        "storage_and_compression": dict(STORAGE_COMPRESSION_SQL),
    }


def _catalog_member_sets(repository_root: Path) -> dict[str, set[str]]:
    path = repository_root.resolve(strict=True) / _COLUMN_STRUCTURE_CATALOG
    document = yaml.safe_load(path.read_text(encoding="utf-8"))
    result: dict[str, set[str]] = {}
    for dimension in document["dimensions"]:
        if "members" not in dimension:
            continue
        result[str(dimension["dimension_id"])] = {
            str(row["member_id"]) for row in dimension["members"]
        }
    return result


def validate_alter_foreign_table_direct_member_renderers(
    repository_root: Path,
    *,
    registry: Mapping[str, Mapping[str, str]] | None = None,
    type_declaration_overrides: Mapping[tuple[str, str], str] | None = None,
) -> None:
    """Fail closed when catalog members and semantic renderers differ."""

    root = Path(repository_root).resolve(strict=True)
    actual_registry = registry or direct_member_renderer_registry()
    member_sets = _catalog_member_sets(root)
    expected_dimensions = {
        "collation",
        "nullability",
        "default_state",
        "generation_mode",
        "identity_mode",
        "storage_and_compression",
    }
    if set(actual_registry) != expected_dimensions:
        raise AlterForeignTableFactorRenderError(
            "missing member renderer dimension"
        )
    for dimension_id in sorted(expected_dimensions):
        rendered_members = set(actual_registry[dimension_id])
        if rendered_members != member_sets[dimension_id]:
            missing = sorted(member_sets[dimension_id] - rendered_members)
            extra = sorted(rendered_members - member_sets[dimension_id])
            raise AlterForeignTableFactorRenderError(
                "missing member renderer: "
                f"dimension={dimension_id} missing={missing} extra={extra}"
            )

    overrides = dict(type_declaration_overrides or {})
    witnesses = load_alter_foreign_table_type_witnesses(root)
    if len(witnesses) != 359:
        raise AlterForeignTableFactorRenderError("type witness count drift")
    identities: set[tuple[str, str]] = set()
    for witness in witnesses:
        identity = (witness.selector_id, witness.member)
        identities.add(identity)
        declaration = overrides.get(identity, witness.declaration_sql)
        if not declaration.strip():
            raise AlterForeignTableFactorRenderError(
                "empty type declaration: "
                f"selector={witness.selector_id} member={witness.member}"
            )
    if len(identities) != 359:
        raise AlterForeignTableFactorRenderError("duplicate type witness")


def _format_sql(template: str, case: AlterForeignTableFactorCase) -> str:
    return template.format(
        prefix=case.object_prefix,
        column_name=f"{case.object_prefix}factor_col",
        other_column_name=f"{case.object_prefix}base_col",
    )


def _format_sql_rows(
    rows: tuple[str, ...],
    case: AlterForeignTableFactorCase,
) -> tuple[str, ...]:
    return tuple(_format_sql(row, case) for row in rows)


@lru_cache(maxsize=None)
def _cached_type_witness_map(
    repository_root: str,
):
    return {
        (row.selector_id, row.member): row
        for row in load_alter_foreign_table_type_witnesses(Path(repository_root))
    }


def _column_catalog_oracle(
    case: AlterForeignTableFactorCase,
    *,
    attribute: str,
) -> tuple[str, ...]:
    table_name = f"{case.object_prefix}ft"
    column_name = f"{case.object_prefix}factor_col"
    return (
        "SELECT EXISTS ("
        "SELECT 1 FROM pg_catalog.pg_attribute AS a "
        f"WHERE a.attrelid = '{table_name}'::regclass "
        f"AND a.attname = '{column_name}' AND NOT a.attisdropped"
        f") AS {attribute};",
    )


def _dependency_sql(
    case: AlterForeignTableFactorCase,
    dimension_id: str,
    member: str,
) -> tuple[tuple[str, ...], tuple[str, ...]]:
    prefix = case.object_prefix
    if dimension_id == "collation":
        if member == "explicit_user_defined_collation":
            return (
                (f'CREATE COLLATION {prefix}collation FROM pg_catalog."C";',),
                (f"DROP COLLATION IF EXISTS {prefix}collation;",),
            )
        if member == "quoted_collation_name":
            name = f'"{prefix}Mixed Collation"'
            return (
                (f'CREATE COLLATION {name} FROM pg_catalog."C";',),
                (f"DROP COLLATION IF EXISTS {name};",),
            )
        if member == "schema_qualified_collation_name":
            schema = f"{prefix}collation_schema"
            name = f"{schema}.{prefix}collation"
            return (
                (
                    f"CREATE SCHEMA {schema};",
                    f'CREATE COLLATION {name} FROM pg_catalog."C";',
                ),
                (
                    f"DROP COLLATION IF EXISTS {name};",
                    f"DROP SCHEMA IF EXISTS {schema};",
                ),
            )
        if member == "encoding_incompatible_collation":
            return (
                (
                    f"CREATE COLLATION {prefix}encoding_collation "
                    "(provider = libc, locale = 'C');",
                ),
                (f"DROP COLLATION IF EXISTS {prefix}encoding_collation;",),
            )
    if dimension_id == "default_state":
        if member == "sequence_nextval_dependency":
            return (
                (f"CREATE SEQUENCE {prefix}default_seq;",),
                (f"DROP SEQUENCE IF EXISTS {prefix}default_seq;",),
            )
        if member == "user_function_dependency":
            return (
                (
                    f"CREATE FUNCTION {prefix}default_fn() RETURNS integer "
                    "LANGUAGE sql IMMUTABLE AS 'SELECT 7';",
                ),
                (f"DROP FUNCTION IF EXISTS {prefix}default_fn();",),
            )
    if dimension_id == "generation_mode" and member == "generated_column_reference":
        return (
            (
                f"ALTER FOREIGN TABLE {prefix}ft ADD COLUMN "
                f"{prefix}generated_col integer GENERATED ALWAYS AS (7) STORED;",
            ),
            (),
        )
    return (), ()


def _type_witness(
    case: AlterForeignTableFactorCase,
    repository_root: Path,
) -> AlterForeignTableFactorWitness:
    selector_id, member = case.factor_value.split("::", 1)
    witnesses = _cached_type_witness_map(str(repository_root.resolve()))
    try:
        type_witness = witnesses[(selector_id, member)]
    except KeyError as exc:
        raise AlterForeignTableFactorRenderError(
            f"missing type witness: {selector_id}::{member}"
        ) from exc
    declaration = _format_sql(type_witness.declaration_sql, case).strip()
    if not declaration:
        raise AlterForeignTableFactorRenderError("empty type declaration")
    column_name = f"{case.object_prefix}factor_col"
    if case.consumer_action_id == "add_column":
        target = f"ADD COLUMN {column_name} {declaration}"
    elif case.consumer_action_id == "alter_column_type":
        target = f"ALTER COLUMN {column_name} TYPE {declaration}"
    else:
        raise AlterForeignTableFactorRenderError(
            f"type factor routed to unsupported action {case.consumer_action_id}"
        )
    return AlterForeignTableFactorWitness(
        primary_obligation_id=case.primary_obligation_id,
        setup_sql=_format_sql_rows(type_witness.setup_sql, case),
        target_sql_fragment=target,
        oracle_sql=_column_catalog_oracle(case, attribute="type_factor_applied"),
        cleanup_sql=_format_sql_rows(type_witness.cleanup_sql, case),
        semantic_locus="target.type_name",
        outcome=case.outcome,
        expected_sqlstate=case.expected_sqlstate,
    )


def _direct_witness(
    case: AlterForeignTableFactorCase,
    registry: Mapping[str, Mapping[str, str]],
) -> AlterForeignTableFactorWitness:
    dimension_id = case.factor_key
    member = case.factor_value
    try:
        raw_fragment = registry[dimension_id][member]
    except KeyError as exc:
        raise AlterForeignTableFactorRenderError(
            f"missing member renderer: {dimension_id}={member}"
        ) from exc
    fragment = _format_sql(raw_fragment, case).strip()
    column_name = f"{case.object_prefix}factor_col"
    setup_sql, cleanup_sql = _dependency_sql(case, dimension_id, member)
    semantic_locus = "target.column_definition"

    if dimension_id == "collation":
        base_type = (
            "integer" if member == "collation_on_noncollatable_type" else "text"
        )
        if case.consumer_action_id == "add_column":
            target = f"ADD COLUMN {column_name} {base_type} {fragment}".strip()
        else:
            target = f"ALTER COLUMN {column_name} TYPE {base_type} {fragment}".strip()
            semantic_locus = "target.type_name"
    elif dimension_id == "nullability":
        if case.consumer_action_id == "add_column":
            target = f"ADD COLUMN {column_name} integer {fragment}".strip()
        elif case.consumer_action_id == "set_not_null":
            target = (
                f"ADD COLUMN {case.object_prefix}probe_col integer {fragment}, "
                f"ALTER COLUMN {column_name} SET NOT NULL"
            ).strip()
        elif case.consumer_action_id == "drop_not_null":
            target = (
                f"ADD COLUMN {case.object_prefix}probe_col integer {fragment}, "
                f"ALTER COLUMN {column_name} DROP NOT NULL"
            ).strip()
        elif case.consumer_action_id == "add_constraint":
            target = (
                f"ADD COLUMN {case.object_prefix}probe_col integer {fragment}, "
                f"ADD CONSTRAINT {case.object_prefix}not_null "
                f"NOT NULL {column_name}"
            ).strip()
        else:
            raise AlterForeignTableFactorRenderError("invalid nullability action")
    elif dimension_id == "default_state":
        expression = fragment.removeprefix("DEFAULT ")
        if case.consumer_action_id == "add_column":
            target = f"ADD COLUMN {column_name} integer {fragment}".strip()
        elif case.consumer_action_id == "set_default":
            target = (
                f"ALTER COLUMN {column_name} SET DEFAULT "
                f"{expression or 'NULL'}"
            )
        elif case.consumer_action_id == "drop_default":
            target = (
                f"ADD COLUMN {case.object_prefix}probe_col integer {fragment}, "
                f"ALTER COLUMN {column_name} DROP DEFAULT"
            ).strip()
        else:
            raise AlterForeignTableFactorRenderError("invalid default action")
    elif dimension_id == "generation_mode":
        target = f"ADD COLUMN {column_name} integer {fragment}".strip()
    elif dimension_id == "identity_mode":
        base_type = "text" if member == "identity_on_non_integer_type" else "bigint"
        target = f"ADD COLUMN {column_name} {base_type} {fragment}".strip()
    elif dimension_id == "storage_and_compression":
        base_type = (
            "integer"
            if member == "incompatible_fixed_length_storage_mode"
            else "text"
        )
        if case.consumer_action_id == "add_column":
            target = f"ADD COLUMN {column_name} {base_type} {fragment}".strip()
        elif case.consumer_action_id == "set_storage":
            storage_mode = {
                "storage_default": "DEFAULT",
                "storage_plain": "PLAIN",
                "storage_main": "MAIN",
                "storage_extended": "EXTENDED",
                "storage_external": "EXTERNAL",
                "incompatible_fixed_length_storage_mode": "EXTERNAL",
            }.get(member, "DEFAULT")
            target = (
                f"ADD COLUMN {case.object_prefix}probe_col {base_type} {fragment}, "
                f"ALTER COLUMN {column_name} SET STORAGE {storage_mode}"
            ).strip()
        else:
            raise AlterForeignTableFactorRenderError("invalid storage action")
    else:
        raise AlterForeignTableFactorRenderError(
            f"unsupported direct dimension: {dimension_id}"
        )

    if not target.strip():
        raise AlterForeignTableFactorRenderError("empty target SQL fragment")
    return AlterForeignTableFactorWitness(
        primary_obligation_id=case.primary_obligation_id,
        setup_sql=setup_sql,
        target_sql_fragment=target,
        oracle_sql=_column_catalog_oracle(case, attribute="column_factor_applied"),
        cleanup_sql=cleanup_sql,
        semantic_locus=semantic_locus,
        outcome=case.outcome,
        expected_sqlstate=case.expected_sqlstate,
    )


def resolve_alter_foreign_table_factor_witness(
    case: AlterForeignTableFactorCase,
    repository_root: Path,
    *,
    registry: Mapping[str, Mapping[str, str]] | None = None,
) -> AlterForeignTableFactorWitness:
    """Resolve a planned column-definition case from frozen factor identity."""

    root = Path(repository_root).resolve(strict=True)
    if case.factor_key == "data_type_and_typmod":
        return _type_witness(case, root)
    actual_registry = registry or direct_member_renderer_registry()
    if case.factor_key not in actual_registry:
        raise AlterForeignTableFactorRenderError(
            f"factor renderer not implemented: {case.factor_key}"
        )
    return _direct_witness(case, actual_registry)


__all__ = [
    "AlterForeignTableFactorRenderError",
    "AlterForeignTableFactorWitness",
    "COLLATION_SQL",
    "NULLABILITY_SQL",
    "DEFAULT_SQL",
    "GENERATION_SQL",
    "IDENTITY_SQL",
    "STORAGE_COMPRESSION_SQL",
    "direct_member_renderer_registry",
    "resolve_alter_foreign_table_factor_witness",
    "validate_alter_foreign_table_direct_member_renderers",
]
