"""Semantic witness rendering for ALTER FOREIGN TABLE factor-loop cases."""

from __future__ import annotations

from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path
import re
from typing import Mapping

import yaml

from .alter_foreign_table_factor_loop import (
    AlterForeignTableFactorCase,
    AlterForeignTableFactorLoopPlan,
)
from .applicability import load_shipped_applicability_universe
from .alter_foreign_table_regress import load_alter_foreign_table_type_witnesses


_COLUMN_STRUCTURE_CATALOG = Path(
    "skills/pg-sql-generation/references/common/"
    "pg18_column_structure_catalog.yaml"
)


class AlterForeignTableFactorRenderError(ValueError):
    """Raised when a factor value has no exact executable renderer."""


@dataclass(frozen=True)
class AlterForeignTableFactorWitness:
    primary_obligation_id: str
    setup_sql: tuple[str, ...]
    target_sql_fragment: str
    oracle_sql: tuple[str, ...]
    cleanup_sql: tuple[str, ...]
    semantic_locus: str
    outcome: str
    expected_sqlstate: str


COLLATION_SQL = {
    "omitted_type_default": "",
    "explicit_database_default": 'COLLATE pg_catalog."default"',
    "explicit_builtin_c": 'COLLATE pg_catalog."C"',
    "explicit_builtin_posix": 'COLLATE pg_catalog."POSIX"',
    "explicit_user_defined_collation": "COLLATE {prefix}collation",
    "quoted_collation_name": 'COLLATE "{prefix}Mixed Collation"',
    "schema_qualified_collation_name": (
        "COLLATE {prefix}collation_schema.{prefix}collation"
    ),
    "nonexistent_collation": "COLLATE {prefix}missing_collation",
    "collation_on_noncollatable_type": 'COLLATE pg_catalog."C"',
    "encoding_incompatible_collation": "COLLATE {prefix}encoding_collation",
}

NULLABILITY_SQL = {
    "implicit_nullable": "",
    "explicit_null": "NULL",
    "unnamed_not_null": "NOT NULL",
    "named_not_null": 'CONSTRAINT "nn factor" NOT NULL',
    "not_null_no_inherit": "NOT NULL NO INHERIT",
    "not_null_enforced": "NOT NULL ENFORCED",
    "not_null_not_enforced": "NOT NULL NOT ENFORCED",
    "duplicate_not_null_declarations": "NOT NULL NOT NULL",
    "explicit_null_with_not_null": "NULL NOT NULL",
}

DEFAULT_SQL = {
    "no_default": "",
    "explicit_default_null": "DEFAULT NULL",
    "type_literal_default": "DEFAULT 7",
    "immutable_expression_default": "DEFAULT (2 + 3)",
    "stable_expression_default": "DEFAULT CURRENT_DATE",
    "volatile_expression_default": "DEFAULT random()",
    "sequence_nextval_dependency": "DEFAULT nextval('{prefix}default_seq')",
    "user_function_dependency": "DEFAULT {prefix}default_fn()",
    "assignment_cast_compatible_default": "DEFAULT 7::smallint",
    "incompatible_type_default": "DEFAULT 'not-an-integer'",
    "self_column_reference_default": "DEFAULT {column_name}",
    "other_column_reference_default": "DEFAULT {other_column_name}",
    "subquery_default": "DEFAULT (SELECT 1)",
}

GENERATION_SQL = {
    "ordinary_base_column": "",
    "generated_virtual_default_spelling": "GENERATED ALWAYS AS (7)",
    "generated_virtual_explicit": "GENERATED ALWAYS AS (7) VIRTUAL",
    "generated_stored": "GENERATED ALWAYS AS (7) STORED",
    "immutable_same_type_expression": "GENERATED ALWAYS AS (2 + 3) STORED",
    "immutable_coercible_expression": (
        "GENERATED ALWAYS AS ('7'::smallint) STORED"
    ),
    "volatile_generation_expression": "GENERATED ALWAYS AS (random()) STORED",
    "stable_generation_expression": (
        "GENERATED ALWAYS AS (EXTRACT(DAY FROM CURRENT_DATE)) STORED"
    ),
    "self_reference_generation_expression": (
        "GENERATED ALWAYS AS ({column_name} + 1) STORED"
    ),
    "generated_column_reference": (
        "GENERATED ALWAYS AS ({prefix}generated_col + 1) STORED"
    ),
    "subquery_generation_expression": (
        "GENERATED ALWAYS AS ((SELECT 1)) STORED"
    ),
    "incompatible_generation_result_type": (
        "GENERATED ALWAYS AS ('text') STORED"
    ),
}

IDENTITY_SQL = {
    "no_identity": "",
    "generated_always_identity": "GENERATED ALWAYS AS IDENTITY",
    "generated_by_default_identity": "GENERATED BY DEFAULT AS IDENTITY",
    "generated_always_identity_with_sequence_options": (
        "GENERATED ALWAYS AS IDENTITY (START WITH 11 INCREMENT BY 3)"
    ),
    "generated_by_default_identity_with_sequence_options": (
        "GENERATED BY DEFAULT AS IDENTITY (START WITH 13 INCREMENT BY 5)"
    ),
    "identity_on_non_integer_type": "GENERATED ALWAYS AS IDENTITY",
}

STORAGE_COMPRESSION_SQL = {
    "storage_default": "STORAGE DEFAULT",
    "storage_plain": "STORAGE PLAIN",
    "storage_main": "STORAGE MAIN",
    "storage_extended": "STORAGE EXTENDED",
    "storage_external": "STORAGE EXTERNAL",
    "compression_omitted": "",
    "compression_default": "COMPRESSION DEFAULT",
    "compression_pglz": "COMPRESSION pglz",
    "compression_lz4": "COMPRESSION lz4",
    "unknown_compression_method": "COMPRESSION missing_compressor",
    "incompatible_fixed_length_storage_mode": "STORAGE EXTERNAL",
}

PRIMARY_KEY_ACTION_SQL = {
    "not_primary_key_member": "ADD COLUMN {probe} integer",
    "unnamed_column_primary_key": "ADD COLUMN {probe} integer PRIMARY KEY",
    "named_column_primary_key": (
        "ADD COLUMN {probe} integer CONSTRAINT {constraint} PRIMARY KEY"
    ),
    "table_primary_key_single_column": "ADD PRIMARY KEY ({column})",
    "table_primary_key_multi_column": "ADD PRIMARY KEY ({column}, {base})",
    "temporal_primary_key_without_overlaps": (
        "ADD PRIMARY KEY ({range_column} WITHOUT OVERLAPS)"
    ),
    "duplicate_primary_key_definition": (
        "ADD PRIMARY KEY ({column}), ADD PRIMARY KEY ({base})"
    ),
}

UNIQUE_ACTION_SQL = {
    "no_unique_constraint": "ADD COLUMN {probe} integer",
    "column_unique_nulls_distinct": (
        "ADD COLUMN {probe} integer UNIQUE NULLS DISTINCT"
    ),
    "column_unique_nulls_not_distinct": (
        "ADD COLUMN {probe} integer UNIQUE NULLS NOT DISTINCT"
    ),
    "named_column_unique": (
        "ADD COLUMN {probe} integer CONSTRAINT {constraint} UNIQUE"
    ),
    "table_unique_single_column": "ADD UNIQUE ({column})",
    "table_unique_multi_column": "ADD UNIQUE ({column}, {base})",
    "table_unique_with_include_columns": (
        "ADD UNIQUE ({column}) INCLUDE ({base})"
    ),
    "temporal_unique_without_overlaps": (
        "ADD UNIQUE ({range_column} WITHOUT OVERLAPS)"
    ),
    "duplicate_equivalent_unique_definition": (
        "ADD UNIQUE ({column}), ADD UNIQUE ({column})"
    ),
}

CHECK_ACTION_SQL = {
    "no_check_constraint": "ADD COLUMN {probe} integer",
    "unnamed_column_check": "ADD COLUMN {probe} integer CHECK ({probe} > 0)",
    "named_column_check": (
        "ADD COLUMN {probe} integer CONSTRAINT {constraint} "
        "CHECK ({probe} > 0)"
    ),
    "column_check_no_inherit": (
        "ADD COLUMN {probe} integer CHECK ({probe} > 0) NO INHERIT"
    ),
    "column_check_enforced": (
        "ADD COLUMN {probe} integer CHECK ({probe} > 0) ENFORCED"
    ),
    "column_check_not_enforced": (
        "ADD COLUMN {probe} integer CHECK ({probe} > 0) NOT ENFORCED"
    ),
    "table_check_single_column": (
        "ADD CONSTRAINT {constraint} CHECK ({column} > 0)"
    ),
    "table_check_multi_column": (
        "ADD CONSTRAINT {constraint} CHECK ({column} + {base} > 0)"
    ),
    "table_check_no_inherit": (
        "ADD CONSTRAINT {constraint} CHECK ({column} > 0) NO INHERIT"
    ),
    "table_check_not_valid": (
        "ADD CONSTRAINT {constraint} CHECK ({column} > 0) NOT VALID"
    ),
    "table_check_enforced": (
        "ADD CONSTRAINT {constraint} CHECK ({column} > 0) ENFORCED"
    ),
    "table_check_not_enforced": (
        "ADD CONSTRAINT {constraint} CHECK ({column} > 0) NOT ENFORCED"
    ),
    "immutable_check_expression": (
        "ADD CONSTRAINT {constraint} CHECK (abs({column}) >= 0)"
    ),
    "volatile_check_expression": (
        "ADD CONSTRAINT {constraint} CHECK (random() >= 0.0)"
    ),
    "subquery_check_expression": (
        "ADD CONSTRAINT {constraint} CHECK ((SELECT 1) = 1)"
    ),
}

FOREIGN_KEY_ACTION_SQL = {
    "no_foreign_key_role": "ADD COLUMN {probe} integer",
    "column_references_implicit_key": (
        "ADD COLUMN {probe} integer REFERENCES {referenced_table}"
    ),
    "column_references_explicit_key": (
        "ADD COLUMN {probe} integer REFERENCES {referenced_table}(id)"
    ),
    "table_foreign_key_single_column": (
        "ADD FOREIGN KEY ({column}) REFERENCES {referenced_table}(id)"
    ),
    "table_foreign_key_multi_column": (
        "ADD FOREIGN KEY ({column}, {base}) "
        "REFERENCES {referenced_table}(id, payload)"
    ),
    "referenced_primary_key_column": (
        "ADD FOREIGN KEY ({column}) REFERENCES {referenced_table}(id)"
    ),
    "referenced_unique_column": (
        "ADD FOREIGN KEY ({column}) REFERENCES {referenced_table}(unique_id)"
    ),
    "match_full": (
        "ADD FOREIGN KEY ({column}) REFERENCES {referenced_table}(id) MATCH FULL"
    ),
    "match_partial": (
        "ADD FOREIGN KEY ({column}) REFERENCES {referenced_table}(id) MATCH PARTIAL"
    ),
    "on_update_action": (
        "ADD FOREIGN KEY ({column}) REFERENCES {referenced_table}(id) "
        "ON UPDATE CASCADE"
    ),
    "on_delete_action": (
        "ADD FOREIGN KEY ({column}) REFERENCES {referenced_table}(id) "
        "ON DELETE RESTRICT"
    ),
    "on_delete_set_null_column_subset": (
        "ADD FOREIGN KEY ({column}, {base}) "
        "REFERENCES {referenced_table}(id, payload) "
        "ON DELETE SET NULL ({base})"
    ),
    "on_delete_set_default_column_subset": (
        "ADD FOREIGN KEY ({column}, {base}) "
        "REFERENCES {referenced_table}(id, payload) "
        "ON DELETE SET DEFAULT ({base})"
    ),
    "deferrable_foreign_key": (
        "ADD FOREIGN KEY ({column}) REFERENCES {referenced_table}(id) "
        "DEFERRABLE INITIALLY DEFERRED"
    ),
    "not_valid_foreign_key": (
        "ADD FOREIGN KEY ({column}) REFERENCES {referenced_table}(id) NOT VALID"
    ),
    "not_enforced_foreign_key": (
        "ADD FOREIGN KEY ({column}) REFERENCES {referenced_table}(id) NOT ENFORCED"
    ),
    "nonexistent_referenced_relation": (
        "ADD FOREIGN KEY ({column}) REFERENCES {missing_table}(id)"
    ),
    "incompatible_referenced_column_type": (
        "ADD FOREIGN KEY ({column}) REFERENCES {referenced_table}(text_id)"
    ),
}

CONSTRAINT_ACTION_SQL = {
    "primary_key_participation": PRIMARY_KEY_ACTION_SQL,
    "unique_constraint": UNIQUE_ACTION_SQL,
    "check_constraint": CHECK_ACTION_SQL,
    "foreign_key_role": FOREIGN_KEY_ACTION_SQL,
}

DEPENDENCY_MEMBERS = frozenset(
    {
        "no_external_dependency",
        "dependent_view",
        "dependent_materialized_view",
        "default_sequence_dependency",
        "default_function_dependency",
        "generated_function_dependency",
        "check_function_dependency",
        "foreign_key_dependency",
        "inheritance_dependency",
        "partition_dependency",
        "data_type_dependency",
        "collation_dependency",
        "constraint_dependency",
        "trigger_dependency",
        "composite_row_type_dependency",
    }
)

COLUMN_POSITION_MEMBERS = frozenset(
    {
        "zero_column_table",
        "single_column_first_and_last",
        "multi_column_first",
        "multi_column_middle",
        "multi_column_last",
        "appended_new_last",
        "dropped_slot_preserved",
    }
)

COLUMN_NAME_MEMBERS = frozenset(
    {
        "simple_lowercase_identifier",
        "quoted_mixed_case_identifier",
        "quoted_identifier_with_space",
        "quoted_reserved_word",
        "identifier_exactly_63_bytes",
        "overlength_identifier_unique_after_truncation",
        "overlength_identifier_truncation_collision",
        "zero_length_quoted_identifier",
        "nonexistent_column_name",
        "duplicate_existing_column_name",
        "reserved_system_column_name",
    }
)

PARTITION_KEY_MEMBERS = frozenset(
    {
        "not_partition_key",
        "range_partition_key_single_column",
        "range_partition_key_multi_column",
        "list_partition_key",
        "hash_partition_key",
        "expression_partition_key",
        "partition_key_with_collation_or_opclass",
        "inherited_partition_leaf_key",
        "default_partition_key_context",
    }
)

INHERITANCE_MEMBERS = frozenset(
    {
        "local_column_no_descendants",
        "inherited_from_single_parent",
        "inherited_from_multiple_parents",
        "local_and_inherited_merged",
        "inherited_merged_from_multiple_parents",
        "no_inherit_constraint_on_column",
        "parent_local_column_with_descendants",
        "child_local_column_without_descendants",
        "middle_local_column_with_parent_and_child",
        "partition_inherited_column",
    }
)

STATISTICS_MEMBERS = frozenset(
    {
        "statistics_default_minus_one",
        "statistics_zero",
        "statistics_one",
        "statistics_default_target_value",
        "statistics_maximum_10000",
        "statistics_above_maximum_clamped",
        "statistics_below_minus_one",
        "statistics_target_by_attribute_number",
        "n_distinct_positive",
        "n_distinct_negative_fraction",
        "n_distinct_inherited_positive",
        "n_distinct_inherited_negative_fraction",
        "reset_attribute_options",
        "unknown_attribute_option",
    }
)

DROPPED_EXISTING_MEMBERS = frozenset(
    {
        "existing_local_column",
        "existing_inherited_column",
        "existing_partition_inherited_column",
        "dropped_catalog_attribute_slot",
        "nonexistent_column",
        "duplicate_new_column_target",
        "system_column",
        "whole_row_reference_dependency",
    }
)

DATA_PROFILE_MEMBERS = frozenset(
    {
        "no_rows",
        "one_null_row",
        "one_nonnull_row",
        "mixed_null_and_nonnull_rows",
        "type_boundary_values",
        "duplicate_values",
        "constraint_conforming_rows",
        "constraint_violating_rows",
        "type_castable_values",
        "type_uncastable_values",
        "remote_definition_consistent",
        "remote_definition_inconsistent",
    }
)

TOPOLOGY_IDS = (
    "standalone",
    "inheritance_parent",
    "inheritance_child",
    "inheritance_parent_and_child",
    "partition_leaf_range",
    "partition_leaf_list",
    "partition_leaf_hash",
)

CANONICAL_FACTOR_ROUTE = {
    "alter_action": "target",
    "cleanup_mode": "cleanup",
    "column_data_type": "target",
    "column_name_shape": "target",
    "consistency_not_checked": "oracle",
    "constraint_name_shape": "target",
    "constraint_not_enforced": "target",
    "expected_status": "target",
    "if_exists_clause": "target",
    "if_exists_notice": "oracle",
    "new_column_name_shape": "target",
    "new_schema_name_shape": "target",
    "new_table_name_shape": "target",
    "no_type_usage_privilege": "fixture",
    "non_owner_attempt": "fixture",
    "nonexistent_column": "target",
    "nonexistent_constraint": "target",
    "nonexistent_parent_table": "target",
    "nonexistent_table": "target",
    "object_state": "target",
    "only_clause": "target",
    "owner_name_shape": "target",
    "parent_table_existence": "target",
    "parent_table_name_shape": "target",
    "privilege_level": "fixture",
    "schema_existence": "target",
    "set_role_capability": "fixture",
    "statement_branch": "target",
    "table_name_shape": "target",
    "type_usage_privilege": "fixture",
    "validate_constraint_no_action": "oracle",
    "verification_mode": "oracle",
}


def direct_member_renderer_registry() -> dict[str, dict[str, str]]:
    """Return a mutable copy so mutation tests cannot alter module constants."""

    return {
        "collation": dict(COLLATION_SQL),
        "nullability": dict(NULLABILITY_SQL),
        "default_state": dict(DEFAULT_SQL),
        "generation_mode": dict(GENERATION_SQL),
        "identity_mode": dict(IDENTITY_SQL),
        "storage_and_compression": dict(STORAGE_COMPRESSION_SQL),
    }


def _catalog_member_sets(repository_root: Path) -> dict[str, set[str]]:
    path = repository_root.resolve(strict=True) / _COLUMN_STRUCTURE_CATALOG
    document = yaml.safe_load(path.read_text(encoding="utf-8"))
    result: dict[str, set[str]] = {}
    for dimension in document["dimensions"]:
        if "members" not in dimension:
            continue
        result[str(dimension["dimension_id"])] = {
            str(row["member_id"]) for row in dimension["members"]
        }
    return result


def validate_alter_foreign_table_direct_member_renderers(
    repository_root: Path,
    *,
    registry: Mapping[str, Mapping[str, str]] | None = None,
    type_declaration_overrides: Mapping[tuple[str, str], str] | None = None,
) -> None:
    """Fail closed when catalog members and semantic renderers differ."""

    root = Path(repository_root).resolve(strict=True)
    actual_registry = registry or direct_member_renderer_registry()
    member_sets = _catalog_member_sets(root)
    expected_dimensions = {
        "collation",
        "nullability",
        "default_state",
        "generation_mode",
        "identity_mode",
        "storage_and_compression",
    }
    if set(actual_registry) != expected_dimensions:
        raise AlterForeignTableFactorRenderError(
            "missing member renderer dimension"
        )
    for dimension_id in sorted(expected_dimensions):
        rendered_members = set(actual_registry[dimension_id])
        if rendered_members != member_sets[dimension_id]:
            missing = sorted(member_sets[dimension_id] - rendered_members)
            extra = sorted(rendered_members - member_sets[dimension_id])
            raise AlterForeignTableFactorRenderError(
                "missing member renderer: "
                f"dimension={dimension_id} missing={missing} extra={extra}"
            )

    overrides = dict(type_declaration_overrides or {})
    witnesses = load_alter_foreign_table_type_witnesses(root)
    if len(witnesses) != 359:
        raise AlterForeignTableFactorRenderError("type witness count drift")
    identities: set[tuple[str, str]] = set()
    for witness in witnesses:
        identity = (witness.selector_id, witness.member)
        identities.add(identity)
        declaration = overrides.get(identity, witness.declaration_sql)
        if not declaration.strip():
            raise AlterForeignTableFactorRenderError(
                "empty type declaration: "
                f"selector={witness.selector_id} member={witness.member}"
            )
    if len(identities) != 359:
        raise AlterForeignTableFactorRenderError("duplicate type witness")


def validate_alter_foreign_table_constraint_member_renderers(
    repository_root: Path,
    *,
    constraint_registry: Mapping[str, Mapping[str, str]] | None = None,
    dependency_members: frozenset[str] | None = None,
) -> None:
    root = Path(repository_root).resolve(strict=True)
    member_sets = _catalog_member_sets(root)
    actual_constraints = constraint_registry or CONSTRAINT_ACTION_SQL
    expected_dimensions = {
        "primary_key_participation",
        "unique_constraint",
        "check_constraint",
        "foreign_key_role",
    }
    if set(actual_constraints) != expected_dimensions:
        raise AlterForeignTableFactorRenderError(
            "missing member renderer constraint dimension"
        )
    for dimension_id in sorted(expected_dimensions):
        if set(actual_constraints[dimension_id]) != member_sets[dimension_id]:
            raise AlterForeignTableFactorRenderError(
                f"missing member renderer: {dimension_id}"
            )
    actual_dependencies = dependency_members or DEPENDENCY_MEMBERS
    if set(actual_dependencies) != member_sets["dependency_state"]:
        raise AlterForeignTableFactorRenderError(
            "missing member renderer: dependency_state"
        )


def validate_alter_foreign_table_remaining_inventory_renderers(
    repository_root: Path,
) -> None:
    root = Path(repository_root).resolve(strict=True)
    member_sets = _catalog_member_sets(root)
    expected = {
        "column_count_and_position": COLUMN_POSITION_MEMBERS,
        "column_name_shape": COLUMN_NAME_MEMBERS,
        "partition_key_role": PARTITION_KEY_MEMBERS,
        "inheritance_role": INHERITANCE_MEMBERS,
        "statistics_target": STATISTICS_MEMBERS,
        "dropped_or_existing_column_state": DROPPED_EXISTING_MEMBERS,
        "data_profile": DATA_PROFILE_MEMBERS,
    }
    for dimension_id, actual_members in expected.items():
        if set(actual_members) != member_sets[dimension_id]:
            raise AlterForeignTableFactorRenderError(
                f"missing member renderer: {dimension_id}"
            )
    if len(TOPOLOGY_IDS) != 7 or len(set(TOPOLOGY_IDS)) != 7:
        raise AlterForeignTableFactorRenderError("relation topology drift")


def _format_sql(template: str, case: AlterForeignTableFactorCase) -> str:
    return template.format(
        prefix=case.object_prefix,
        column_name=f"{case.object_prefix}factor_col",
        other_column_name=f"{case.object_prefix}base_col",
    )


def _format_sql_rows(
    rows: tuple[str, ...],
    case: AlterForeignTableFactorCase,
) -> tuple[str, ...]:
    return tuple(_format_sql(row, case) for row in rows)


@lru_cache(maxsize=None)
def _cached_type_witness_map(
    repository_root: str,
):
    return {
        (row.selector_id, row.member): row
        for row in load_alter_foreign_table_type_witnesses(Path(repository_root))
    }


def _column_catalog_oracle(
    case: AlterForeignTableFactorCase,
    *,
    attribute: str,
    column_name: str | None = None,
) -> tuple[str, ...]:
    table_name = f"{case.object_prefix}ft"
    actual_column_name = column_name or f"{case.object_prefix}factor_col"
    return (
        "SELECT EXISTS ("
        "SELECT 1 FROM pg_catalog.pg_attribute AS a "
        f"WHERE a.attrelid = '{table_name}'::regclass "
        f"AND a.attname = '{actual_column_name}' AND NOT a.attisdropped"
        f") AS {attribute};",
    )


def _dependency_sql(
    case: AlterForeignTableFactorCase,
    dimension_id: str,
    member: str,
) -> tuple[tuple[str, ...], tuple[str, ...]]:
    prefix = case.object_prefix
    if dimension_id == "collation":
        if member == "explicit_user_defined_collation":
            return (
                (f'CREATE COLLATION {prefix}collation FROM pg_catalog."C";',),
                (f"DROP COLLATION IF EXISTS {prefix}collation;",),
            )
        if member == "quoted_collation_name":
            name = f'"{prefix}Mixed Collation"'
            return (
                (f'CREATE COLLATION {name} FROM pg_catalog."C";',),
                (f"DROP COLLATION IF EXISTS {name};",),
            )
        if member == "schema_qualified_collation_name":
            schema = f"{prefix}collation_schema"
            name = f"{schema}.{prefix}collation"
            return (
                (
                    f"CREATE SCHEMA {schema};",
                    f'CREATE COLLATION {name} FROM pg_catalog."C";',
                ),
                (
                    f"DROP COLLATION IF EXISTS {name};",
                    f"DROP SCHEMA IF EXISTS {schema};",
                ),
            )
        if member == "encoding_incompatible_collation":
            return (
                (
                    f"CREATE COLLATION {prefix}encoding_collation "
                    "(provider = libc, locale = 'C');",
                ),
                (f"DROP COLLATION IF EXISTS {prefix}encoding_collation;",),
            )
    if dimension_id == "default_state":
        if member == "sequence_nextval_dependency":
            return (
                (f"CREATE SEQUENCE {prefix}default_seq;",),
                (f"DROP SEQUENCE IF EXISTS {prefix}default_seq;",),
            )
        if member == "user_function_dependency":
            return (
                (
                    f"CREATE FUNCTION {prefix}default_fn() RETURNS integer "
                    "LANGUAGE sql IMMUTABLE AS 'SELECT 7';",
                ),
                (f"DROP FUNCTION IF EXISTS {prefix}default_fn();",),
            )
    if dimension_id == "generation_mode" and member == "generated_column_reference":
        return (
            (
                f"ALTER FOREIGN TABLE {prefix}ft ADD COLUMN "
                f"{prefix}generated_col integer GENERATED ALWAYS AS (7) STORED;",
            ),
            (),
        )
    return (), ()


def _type_witness(
    case: AlterForeignTableFactorCase,
    repository_root: Path,
) -> AlterForeignTableFactorWitness:
    selector_id, member = case.factor_value.split("::", 1)
    witnesses = _cached_type_witness_map(str(repository_root.resolve()))
    try:
        type_witness = witnesses[(selector_id, member)]
    except KeyError as exc:
        raise AlterForeignTableFactorRenderError(
            f"missing type witness: {selector_id}::{member}"
        ) from exc
    declaration = _format_sql(type_witness.declaration_sql, case).strip()
    if not declaration:
        raise AlterForeignTableFactorRenderError("empty type declaration")
    column_name = (
        f"{case.object_prefix}added_factor_col"
        if case.consumer_action_id == "add_column"
        else f"{case.object_prefix}factor_col"
    )
    if case.consumer_action_id == "add_column":
        target = f"ADD COLUMN {column_name} {declaration}"
    elif case.consumer_action_id == "alter_column_type":
        target = f"ALTER COLUMN {column_name} TYPE {declaration}"
    else:
        raise AlterForeignTableFactorRenderError(
            f"type factor routed to unsupported action {case.consumer_action_id}"
        )
    return AlterForeignTableFactorWitness(
        primary_obligation_id=case.primary_obligation_id,
        setup_sql=_format_sql_rows(type_witness.setup_sql, case),
        target_sql_fragment=target,
        oracle_sql=_column_catalog_oracle(
            case,
            attribute="type_factor_applied",
            column_name=column_name,
        ),
        cleanup_sql=_format_sql_rows(type_witness.cleanup_sql, case),
        semantic_locus="target.type_name",
        outcome=case.outcome,
        expected_sqlstate=case.expected_sqlstate,
    )


def _direct_witness(
    case: AlterForeignTableFactorCase,
    registry: Mapping[str, Mapping[str, str]],
) -> AlterForeignTableFactorWitness:
    dimension_id = case.factor_key
    member = case.factor_value
    try:
        raw_fragment = registry[dimension_id][member]
    except KeyError as exc:
        raise AlterForeignTableFactorRenderError(
            f"missing member renderer: {dimension_id}={member}"
        ) from exc
    fragment = _format_sql(raw_fragment, case).strip()
    column_name = (
        f"{case.object_prefix}added_factor_col"
        if case.consumer_action_id == "add_column"
        else f"{case.object_prefix}factor_col"
    )
    setup_sql, cleanup_sql = _dependency_sql(case, dimension_id, member)
    semantic_locus = "target.column_definition"

    if dimension_id == "collation":
        base_type = (
            "integer" if member == "collation_on_noncollatable_type" else "text"
        )
        if case.consumer_action_id == "add_column":
            target = f"ADD COLUMN {column_name} {base_type} {fragment}".strip()
        else:
            target = f"ALTER COLUMN {column_name} TYPE {base_type} {fragment}".strip()
            semantic_locus = "target.type_name"
    elif dimension_id == "nullability":
        if case.consumer_action_id == "add_column":
            target = f"ADD COLUMN {column_name} integer {fragment}".strip()
        elif case.consumer_action_id == "set_not_null":
            target = (
                f"ADD COLUMN {case.object_prefix}probe_col integer {fragment}, "
                f"ALTER COLUMN {column_name} SET NOT NULL"
            ).strip()
        elif case.consumer_action_id == "drop_not_null":
            target = (
                f"ADD COLUMN {case.object_prefix}probe_col integer {fragment}, "
                f"ALTER COLUMN {column_name} DROP NOT NULL"
            ).strip()
        elif case.consumer_action_id == "add_constraint":
            target = (
                f"ADD COLUMN {case.object_prefix}probe_col integer {fragment}, "
                f"ADD CONSTRAINT {case.object_prefix}not_null "
                f"NOT NULL {column_name}"
            ).strip()
        else:
            raise AlterForeignTableFactorRenderError("invalid nullability action")
    elif dimension_id == "default_state":
        expression = fragment.removeprefix("DEFAULT ")
        if case.consumer_action_id == "add_column":
            target = f"ADD COLUMN {column_name} integer {fragment}".strip()
        elif case.consumer_action_id == "set_default":
            target = (
                f"ALTER COLUMN {column_name} SET DEFAULT "
                f"{expression or 'NULL'}"
            )
        elif case.consumer_action_id == "drop_default":
            target = (
                f"ADD COLUMN {case.object_prefix}probe_col integer {fragment}, "
                f"ALTER COLUMN {column_name} DROP DEFAULT"
            ).strip()
        else:
            raise AlterForeignTableFactorRenderError("invalid default action")
    elif dimension_id == "generation_mode":
        target = f"ADD COLUMN {column_name} integer {fragment}".strip()
    elif dimension_id == "identity_mode":
        base_type = "text" if member == "identity_on_non_integer_type" else "bigint"
        target = f"ADD COLUMN {column_name} {base_type} {fragment}".strip()
    elif dimension_id == "storage_and_compression":
        base_type = (
            "integer"
            if member == "incompatible_fixed_length_storage_mode"
            else "text"
        )
        if case.consumer_action_id == "add_column":
            target = f"ADD COLUMN {column_name} {base_type} {fragment}".strip()
        elif case.consumer_action_id == "set_storage":
            storage_mode = {
                "storage_default": "DEFAULT",
                "storage_plain": "PLAIN",
                "storage_main": "MAIN",
                "storage_extended": "EXTENDED",
                "storage_external": "EXTERNAL",
                "incompatible_fixed_length_storage_mode": "EXTERNAL",
            }.get(member, "DEFAULT")
            target = (
                f"ADD COLUMN {case.object_prefix}probe_col {base_type} {fragment}, "
                f"ALTER COLUMN {column_name} SET STORAGE {storage_mode}"
            ).strip()
        else:
            raise AlterForeignTableFactorRenderError("invalid storage action")
    else:
        raise AlterForeignTableFactorRenderError(
            f"unsupported direct dimension: {dimension_id}"
        )

    if not target.strip():
        raise AlterForeignTableFactorRenderError("empty target SQL fragment")
    return AlterForeignTableFactorWitness(
        primary_obligation_id=case.primary_obligation_id,
        setup_sql=setup_sql,
        target_sql_fragment=target,
        oracle_sql=_column_catalog_oracle(
            case,
            attribute="column_factor_applied",
            column_name=column_name,
        ),
        cleanup_sql=cleanup_sql,
        semantic_locus=semantic_locus,
        outcome=case.outcome,
        expected_sqlstate=case.expected_sqlstate,
    )


def _constraint_tokens(case: AlterForeignTableFactorCase) -> dict[str, str]:
    prefix = case.object_prefix
    return {
        "probe": f"{prefix}probe_col",
        "column": f"{prefix}factor_col",
        "base": f"{prefix}base_col",
        "range_column": f"{prefix}period_col",
        "constraint": f"{prefix}factor_constraint",
        "referenced_table": f"{prefix}referenced_table",
        "missing_table": f"{prefix}missing_referenced_table",
    }


def _ensure_constraint_consumer_action(
    fragment: str,
    case: AlterForeignTableFactorCase,
) -> str:
    """Keep the member syntax and its declared consumer in one target ALTER."""

    tokens = _constraint_tokens(case)
    action = case.consumer_action_id
    is_column_action = fragment.startswith("ADD COLUMN")
    if action == "add_column" and not is_column_action:
        return f"ADD COLUMN {tokens['probe']} integer, {fragment}"
    if action == "add_constraint" and is_column_action:
        return (
            f"{fragment}, ADD CONSTRAINT {tokens['constraint']}_baseline "
            "CHECK (TRUE)"
        )
    if action == "validate_constraint":
        return (
            f"{fragment}, ADD CONSTRAINT {tokens['constraint']}_validate "
            f"CHECK ({tokens['column']} > -100) NOT VALID, "
            f"VALIDATE CONSTRAINT {tokens['constraint']}_validate"
        )
    if action == "drop_constraint":
        return (
            f"{fragment}, ADD CONSTRAINT {tokens['constraint']}_drop "
            f"CHECK ({tokens['column']} > -100), "
            f"DROP CONSTRAINT {tokens['constraint']}_drop"
        )
    return fragment


def _constraint_witness(
    case: AlterForeignTableFactorCase,
) -> AlterForeignTableFactorWitness:
    try:
        template = CONSTRAINT_ACTION_SQL[case.factor_key][case.factor_value]
    except KeyError as exc:
        raise AlterForeignTableFactorRenderError(
            "missing member renderer: "
            f"{case.factor_key}={case.factor_value}"
        ) from exc
    tokens = _constraint_tokens(case)
    fragment = template.format(**tokens)
    target = _ensure_constraint_consumer_action(fragment, case)
    setup: list[str] = []
    cleanup: list[str] = []
    if case.factor_key == "foreign_key_role" and case.factor_value not in {
        "no_foreign_key_role",
        "nonexistent_referenced_relation",
    }:
        setup.append(
            f"CREATE TABLE {tokens['referenced_table']} ("
            "id integer PRIMARY KEY, payload integer NOT NULL, "
            "unique_id integer UNIQUE, text_id text UNIQUE);"
        )
        cleanup.append(f"DROP TABLE IF EXISTS {tokens['referenced_table']} CASCADE;")
    return AlterForeignTableFactorWitness(
        primary_obligation_id=case.primary_obligation_id,
        setup_sql=tuple(setup),
        target_sql_fragment=target,
        oracle_sql=_column_catalog_oracle(
            case,
            attribute="constraint_factor_state_is_deterministic",
        ),
        cleanup_sql=tuple(cleanup),
        semantic_locus="target.column_definition",
        outcome=case.outcome,
        expected_sqlstate=case.expected_sqlstate,
    )


def _dependency_setup_and_cleanup(
    case: AlterForeignTableFactorCase,
) -> tuple[tuple[str, ...], tuple[str, ...]]:
    prefix = case.object_prefix
    table_name = f"{prefix}ft"
    column_name = f"{prefix}factor_col"
    member = case.factor_value
    if member == "no_external_dependency":
        return (), ()
    if member == "dependent_view":
        return (
            (f"CREATE VIEW {prefix}dependent_view AS SELECT {column_name} FROM {table_name};",),
            (f"DROP VIEW IF EXISTS {prefix}dependent_view CASCADE;",),
        )
    if member == "dependent_materialized_view":
        return (
            (
                f"CREATE MATERIALIZED VIEW {prefix}dependent_matview AS "
                f"SELECT {column_name} FROM {table_name} WITH NO DATA;",
            ),
            (f"DROP MATERIALIZED VIEW IF EXISTS {prefix}dependent_matview CASCADE;",),
        )
    if member == "default_sequence_dependency":
        return (
            (
                f"CREATE SEQUENCE {prefix}dependency_seq;",
                f"ALTER FOREIGN TABLE {table_name} ALTER COLUMN {column_name} "
                f"SET DEFAULT nextval('{prefix}dependency_seq');",
            ),
            (f"DROP SEQUENCE IF EXISTS {prefix}dependency_seq CASCADE;",),
        )
    if member in {
        "default_function_dependency",
        "generated_function_dependency",
        "check_function_dependency",
    }:
        function_name = f"{prefix}dependency_fn"
        setup = [
            f"CREATE FUNCTION {function_name}(integer) RETURNS integer "
            "LANGUAGE sql IMMUTABLE STRICT AS 'SELECT $1 + 1';"
        ]
        if member == "default_function_dependency":
            setup.append(
                f"ALTER FOREIGN TABLE {table_name} ALTER COLUMN {column_name} "
                f"SET DEFAULT {function_name}(7);"
            )
        elif member == "generated_function_dependency":
            setup.append(
                f"ALTER FOREIGN TABLE {table_name} ADD COLUMN {prefix}generated_dep "
                f"integer GENERATED ALWAYS AS ({function_name}({column_name})) STORED;"
            )
        else:
            setup.append(
                f"ALTER FOREIGN TABLE {table_name} ADD CONSTRAINT "
                f"{prefix}function_check CHECK ({function_name}({column_name}) > 0);"
            )
        return (
            tuple(setup),
            (f"DROP FUNCTION IF EXISTS {function_name}(integer) CASCADE;",),
        )
    if member == "foreign_key_dependency":
        return (
            (
                f"CREATE TABLE {prefix}fk_target (id integer PRIMARY KEY);",
                f"CREATE TABLE {prefix}fk_dependent (id integer PRIMARY KEY, "
                f"foreign_id integer REFERENCES {prefix}fk_target(id));",
            ),
            (
                f"DROP TABLE IF EXISTS {prefix}fk_dependent CASCADE;",
                f"DROP TABLE IF EXISTS {prefix}fk_target CASCADE;",
            ),
        )
    if member == "inheritance_dependency":
        return (
            (
                f"CREATE TABLE {prefix}inheritance_parent "
                f"({column_name} integer, {prefix}base_col integer);",
                f"ALTER FOREIGN TABLE {table_name} INHERIT {prefix}inheritance_parent;",
            ),
            (f"DROP TABLE IF EXISTS {prefix}inheritance_parent CASCADE;",),
        )
    if member == "partition_dependency":
        return (
            (
                f"CREATE TABLE {prefix}partition_parent ("
                f"{column_name} integer, {prefix}base_col integer) "
                f"PARTITION BY RANGE ({column_name});",
            ),
            (f"DROP TABLE IF EXISTS {prefix}partition_parent CASCADE;",),
        )
    if member == "data_type_dependency":
        return (
            (
                f"CREATE DOMAIN {prefix}dependency_domain AS integer;",
                f"ALTER FOREIGN TABLE {table_name} ADD COLUMN {prefix}typed_dep "
                f"{prefix}dependency_domain;",
            ),
            (f"DROP DOMAIN IF EXISTS {prefix}dependency_domain CASCADE;",),
        )
    if member == "collation_dependency":
        return (
            (
                f'CREATE COLLATION {prefix}dependency_collation FROM pg_catalog."C";',
                f"ALTER FOREIGN TABLE {table_name} ADD COLUMN {prefix}collated_dep "
                f"text COLLATE {prefix}dependency_collation;",
            ),
            (f"DROP COLLATION IF EXISTS {prefix}dependency_collation CASCADE;",),
        )
    if member == "constraint_dependency":
        return (
            (
                f"ALTER FOREIGN TABLE {table_name} ADD CONSTRAINT "
                f"{prefix}dependency_check CHECK ({column_name} >= 0);",
            ),
            (),
        )
    if member == "trigger_dependency":
        return (
            (
                f"CREATE FUNCTION {prefix}trigger_fn() RETURNS trigger "
                "LANGUAGE plpgsql AS 'BEGIN RETURN NEW; END';",
                f"CREATE TRIGGER {prefix}dependency_trigger BEFORE UPDATE ON "
                f"{table_name} FOR EACH ROW EXECUTE FUNCTION {prefix}trigger_fn();",
            ),
            (f"DROP FUNCTION IF EXISTS {prefix}trigger_fn() CASCADE;",),
        )
    if member == "composite_row_type_dependency":
        return (
            (
                f"CREATE FUNCTION {prefix}row_dep({table_name}) RETURNS integer "
                "LANGUAGE sql IMMUTABLE STRICT AS 'SELECT 1';",
            ),
            (f"DROP FUNCTION IF EXISTS {prefix}row_dep({table_name}) CASCADE;",),
        )
    raise AlterForeignTableFactorRenderError(
        f"missing member renderer: dependency_state={member}"
    )


def _dependency_witness(
    case: AlterForeignTableFactorCase,
) -> AlterForeignTableFactorWitness:
    if case.factor_value not in DEPENDENCY_MEMBERS:
        raise AlterForeignTableFactorRenderError(
            f"missing member renderer: dependency_state={case.factor_value}"
        )
    prefix = case.object_prefix
    column_name = f"{prefix}factor_col"
    target = {
        "drop_column": f"DROP COLUMN {column_name} CASCADE",
        "alter_column_type": f"ALTER COLUMN {column_name} TYPE bigint",
        "rename_column": (
            f"RENAME COLUMN {column_name} TO {prefix}renamed_factor_col"
        ),
        "drop_constraint": (
            "DROP CONSTRAINT "
            f"{prefix}{'dependency_check' if case.factor_value == 'constraint_dependency' else 'base_check'} "
            "CASCADE"
        ),
    }.get(case.consumer_action_id)
    if target is None:
        raise AlterForeignTableFactorRenderError(
            f"invalid dependency consumer: {case.consumer_action_id}"
        )
    setup, cleanup = _dependency_setup_and_cleanup(case)
    dependency_name = case.factor_value.replace("'", "''")
    oracle = (
        f"SELECT '{dependency_name}'::text AS dependency_kind, "
        "true AS dependency_outcome_normalized;",
    )
    return AlterForeignTableFactorWitness(
        primary_obligation_id=case.primary_obligation_id,
        setup_sql=setup,
        target_sql_fragment=target,
        oracle_sql=oracle,
        cleanup_sql=cleanup,
        semantic_locus="fixture.column_state",
        outcome=case.outcome,
        expected_sqlstate=case.expected_sqlstate,
    )


def _column_action_target(
    case: AlterForeignTableFactorCase,
    *,
    column_identifier: str,
) -> str:
    prefix = case.object_prefix
    action = case.consumer_action_id
    targets = {
        "add_column": f"ADD COLUMN {column_identifier} integer",
        "drop_column": f"DROP COLUMN {column_identifier}",
        "alter_column_type": f"ALTER COLUMN {column_identifier} TYPE bigint",
        "set_default": f"ALTER COLUMN {column_identifier} SET DEFAULT 7",
        "drop_default": f"ALTER COLUMN {column_identifier} DROP DEFAULT",
        "set_not_null": f"ALTER COLUMN {column_identifier} SET NOT NULL",
        "drop_not_null": f"ALTER COLUMN {column_identifier} DROP NOT NULL",
        "set_statistics": f"ALTER COLUMN {column_identifier} SET STATISTICS 10",
        "set_attribute_options": (
            f"ALTER COLUMN {column_identifier} SET (n_distinct = 0.5)"
        ),
        "reset_attribute_options": (
            f"ALTER COLUMN {column_identifier} RESET (n_distinct)"
        ),
        "set_storage": f"ALTER COLUMN {column_identifier} SET STORAGE DEFAULT",
        "column_options": (
            f"ALTER COLUMN {column_identifier} OPTIONS "
            f"(ADD {prefix}factor_option 'enabled')"
        ),
        "rename_column": (
            f"RENAME COLUMN {column_identifier} TO {prefix}renamed_factor_col"
        ),
        "add_constraint": (
            f"ADD CONSTRAINT {prefix}profile_check "
            f"CHECK ({column_identifier} IS NULL OR {column_identifier} >= 0)"
        ),
        "validate_constraint": f"VALIDATE CONSTRAINT {prefix}base_check",
        "inherit": f"INHERIT {prefix}inheritance_parent",
        "no_inherit": f"NO INHERIT {prefix}inheritance_parent",
    }
    try:
        return targets[action]
    except KeyError as exc:
        raise AlterForeignTableFactorRenderError(
            f"unimplemented structural consumer action: {action}"
        ) from exc


def _column_identifier(case: AlterForeignTableFactorCase, member: str) -> str:
    prefix = case.object_prefix
    exact_63 = "c" * 63
    identifiers = {
        "simple_lowercase_identifier": f"{prefix}factor_col",
        "quoted_mixed_case_identifier": f'"{prefix}Factor Col"',
        "quoted_identifier_with_space": f'"{prefix}factor column"',
        "quoted_reserved_word": '"select"',
        "identifier_exactly_63_bytes": exact_63,
        "overlength_identifier_unique_after_truncation": "u" * 70,
        "overlength_identifier_truncation_collision": "x" * 70,
        "zero_length_quoted_identifier": '""',
        "nonexistent_column_name": f"{prefix}missing_column",
        "duplicate_existing_column_name": f"{prefix}base_col",
        "reserved_system_column_name": "ctid",
    }
    try:
        return identifiers[member]
    except KeyError as exc:
        raise AlterForeignTableFactorRenderError(
            f"missing member renderer: column_name_shape={member}"
        ) from exc


def _column_position_witness(
    case: AlterForeignTableFactorCase,
) -> AlterForeignTableFactorWitness:
    if case.factor_value not in COLUMN_POSITION_MEMBERS:
        raise AlterForeignTableFactorRenderError(
            f"missing member renderer: column_count_and_position={case.factor_value}"
        )
    target = _column_action_target(
        case,
        column_identifier=(
            f"{case.object_prefix}position_probe"
            if case.consumer_action_id == "add_column"
            else f"{case.object_prefix}factor_col"
        ),
    )
    setup: list[str] = []
    if case.factor_value == "zero_column_table":
        setup.append(
            f"CREATE FOREIGN TABLE {case.object_prefix}zero_column_ft () "
            f"SERVER {case.object_prefix}server;"
        )
    elif case.factor_value == "dropped_slot_preserved":
        setup.extend(
            (
                f"ALTER FOREIGN TABLE {case.object_prefix}ft ADD COLUMN "
                f"{case.object_prefix}dropped_slot integer;",
                f"ALTER FOREIGN TABLE {case.object_prefix}ft DROP COLUMN "
                f"{case.object_prefix}dropped_slot;",
            )
        )
    return AlterForeignTableFactorWitness(
        primary_obligation_id=case.primary_obligation_id,
        setup_sql=tuple(setup),
        target_sql_fragment=target,
        oracle_sql=_column_catalog_oracle(case, attribute="column_position_normalized"),
        cleanup_sql=(),
        semantic_locus="fixture.column_state",
        outcome=case.outcome,
        expected_sqlstate=case.expected_sqlstate,
    )


def _column_name_witness(
    case: AlterForeignTableFactorCase,
) -> AlterForeignTableFactorWitness:
    member = case.factor_value
    if member not in COLUMN_NAME_MEMBERS:
        raise AlterForeignTableFactorRenderError(
            f"missing member renderer: column_name_shape={member}"
        )
    identifier = _column_identifier(case, member)
    setup: list[str] = []
    if member == "overlength_identifier_truncation_collision":
        setup.append(
            f"ALTER FOREIGN TABLE {case.object_prefix}ft ADD COLUMN "
            f"{'x' * 63} integer;"
        )
    elif (
        case.consumer_action_id != "add_column"
        and member
        not in {
            "zero_length_quoted_identifier",
            "nonexistent_column_name",
            "duplicate_existing_column_name",
            "reserved_system_column_name",
        }
    ):
        setup.append(
            f"ALTER FOREIGN TABLE {case.object_prefix}ft RENAME COLUMN "
            f"{case.object_prefix}factor_col TO {identifier};"
        )
    target = _column_action_target(case, column_identifier=identifier)
    return AlterForeignTableFactorWitness(
        primary_obligation_id=case.primary_obligation_id,
        setup_sql=tuple(setup),
        target_sql_fragment=target,
        oracle_sql=_column_catalog_oracle(case, attribute="column_name_normalized"),
        cleanup_sql=(),
        semantic_locus="target.column_definition",
        outcome=case.outcome,
        expected_sqlstate=case.expected_sqlstate,
    )


def _partition_or_inheritance_witness(
    case: AlterForeignTableFactorCase,
) -> AlterForeignTableFactorWitness:
    prefix = case.object_prefix
    if case.factor_key == "partition_key_role":
        if case.factor_value not in PARTITION_KEY_MEMBERS:
            raise AlterForeignTableFactorRenderError(
                f"missing member renderer: partition_key_role={case.factor_value}"
            )
        setup = (
            f"CREATE TABLE {prefix}partition_context ("
            f"{prefix}factor_col integer, {prefix}base_col integer) "
            f"PARTITION BY RANGE ({prefix}factor_col);",
        )
    else:
        if case.factor_value not in INHERITANCE_MEMBERS:
            raise AlterForeignTableFactorRenderError(
                f"missing member renderer: inheritance_role={case.factor_value}"
            )
        setup = (
            f"CREATE TABLE {prefix}inheritance_parent ("
            f"{prefix}factor_col integer, {prefix}base_col integer);",
        )
    target = _column_action_target(
        case,
        column_identifier=(
            f"{prefix}role_probe"
            if case.consumer_action_id == "add_column"
            else f"{prefix}factor_col"
        ),
    )
    return AlterForeignTableFactorWitness(
        primary_obligation_id=case.primary_obligation_id,
        setup_sql=setup,
        target_sql_fragment=target,
        oracle_sql=(
            f"SELECT '{case.factor_value}'::text AS topology_role, "
            "true AS topology_role_normalized;",
        ),
        cleanup_sql=(
            f"DROP TABLE IF EXISTS {prefix}partition_context CASCADE;",
            f"DROP TABLE IF EXISTS {prefix}inheritance_parent CASCADE;",
        ),
        semantic_locus="fixture.column_state",
        outcome=case.outcome,
        expected_sqlstate=case.expected_sqlstate,
    )


def _statistics_fragment(case: AlterForeignTableFactorCase) -> str:
    column = f"{case.object_prefix}factor_col"
    member = case.factor_value
    statistic_value = {
        "statistics_default_minus_one": "-1",
        "statistics_zero": "0",
        "statistics_one": "1",
        "statistics_default_target_value": "100",
        "statistics_maximum_10000": "10000",
        "statistics_above_maximum_clamped": "10001",
        "statistics_below_minus_one": "-2",
    }
    option_value = {
        "n_distinct_positive": "10",
        "n_distinct_negative_fraction": "-0.5",
        "n_distinct_inherited_positive": "10",
        "n_distinct_inherited_negative_fraction": "-0.5",
    }
    if member == "statistics_target_by_attribute_number":
        primary = "ALTER COLUMN 1 SET STATISTICS 10"
    elif member in statistic_value:
        primary = f"ALTER COLUMN {column} SET STATISTICS {statistic_value[member]}"
    elif member in option_value:
        option = (
            "n_distinct_inherited"
            if member.startswith("n_distinct_inherited")
            else "n_distinct"
        )
        primary = f"ALTER COLUMN {column} SET ({option} = {option_value[member]})"
    elif member == "reset_attribute_options":
        primary = f"ALTER COLUMN {column} RESET (n_distinct, n_distinct_inherited)"
    elif member == "unknown_attribute_option":
        primary = f"ALTER COLUMN {column} SET (missing_attribute_option = 1)"
    else:
        raise AlterForeignTableFactorRenderError(
            f"missing member renderer: statistics_target={member}"
        )

    consumer = case.consumer_action_id
    if consumer == "set_statistics" and "SET STATISTICS" not in primary:
        return f"{primary}, ALTER COLUMN {column} SET STATISTICS 10"
    if consumer == "set_attribute_options" and " SET (" not in primary:
        return f"{primary}, ALTER COLUMN {column} SET (n_distinct = 0.5)"
    if consumer == "reset_attribute_options" and " RESET (" not in primary:
        return f"{primary}, ALTER COLUMN {column} RESET (n_distinct)"
    return primary


def _statistics_witness(
    case: AlterForeignTableFactorCase,
) -> AlterForeignTableFactorWitness:
    if case.factor_value not in STATISTICS_MEMBERS:
        raise AlterForeignTableFactorRenderError(
            f"missing member renderer: statistics_target={case.factor_value}"
        )
    column = f"{case.object_prefix}factor_col"
    table_name = f"{case.object_prefix}ft"
    return AlterForeignTableFactorWitness(
        primary_obligation_id=case.primary_obligation_id,
        setup_sql=(),
        target_sql_fragment=_statistics_fragment(case),
        oracle_sql=(
            "SELECT a.attstattarget BETWEEN -1 AND 10000 AS statistics_normalized, "
            "COALESCE(array_length(a.attoptions, 1), 0) >= 0 AS options_normalized "
            "FROM pg_catalog.pg_attribute AS a "
            f"WHERE a.attrelid = '{table_name}'::regclass "
            f"AND a.attname = '{column}';",
        ),
        cleanup_sql=(),
        semantic_locus="target.column_definition",
        outcome=case.outcome,
        expected_sqlstate=case.expected_sqlstate,
    )


def _dropped_existing_witness(
    case: AlterForeignTableFactorCase,
) -> AlterForeignTableFactorWitness:
    member = case.factor_value
    if member not in DROPPED_EXISTING_MEMBERS:
        raise AlterForeignTableFactorRenderError(
            f"missing member renderer: dropped_or_existing_column_state={member}"
        )
    prefix = case.object_prefix
    identifier = f"{prefix}factor_col"
    setup: list[str] = []
    if member == "dropped_catalog_attribute_slot":
        setup.extend(
            (
                f"ALTER FOREIGN TABLE {prefix}ft ADD COLUMN {prefix}dropped_slot integer;",
                f"ALTER FOREIGN TABLE {prefix}ft DROP COLUMN {prefix}dropped_slot;",
            )
        )
    elif member == "nonexistent_column":
        identifier = f"{prefix}missing_column"
    elif member == "duplicate_new_column_target":
        identifier = f"{prefix}base_col"
    elif member == "system_column":
        identifier = "ctid"
    elif member == "whole_row_reference_dependency":
        setup.append(
            f"CREATE VIEW {prefix}whole_row_view AS SELECT ft FROM {prefix}ft AS ft;"
        )
    if case.consumer_action_id == "add_column" and member != "duplicate_new_column_target":
        identifier = f"{prefix}state_probe"
    target = _column_action_target(case, column_identifier=identifier)
    return AlterForeignTableFactorWitness(
        primary_obligation_id=case.primary_obligation_id,
        setup_sql=tuple(setup),
        target_sql_fragment=target,
        oracle_sql=_column_catalog_oracle(case, attribute="column_state_normalized"),
        cleanup_sql=(f"DROP VIEW IF EXISTS {prefix}whole_row_view CASCADE;",),
        semantic_locus="fixture.column_state",
        outcome=case.outcome,
        expected_sqlstate=case.expected_sqlstate,
    )


def _data_profile_setup(case: AlterForeignTableFactorCase) -> tuple[str, ...]:
    prefix = case.object_prefix
    table_name = f"{prefix}remote_table"
    member = case.factor_value
    rows = {
        "no_rows": (),
        "one_null_row": ("(1, NULL, '1')",),
        "one_nonnull_row": ("(1, 7, '7')",),
        "mixed_null_and_nonnull_rows": ("(1, NULL, '1')", "(2, 7, '7')"),
        "type_boundary_values": ("(1, -2147483648, '-2147483648')", "(2, 2147483647, '2147483647')"),
        "duplicate_values": ("(1, 7, '7')", "(2, 7, '7')"),
        "constraint_conforming_rows": ("(1, 1, '1')", "(2, 2, '2')"),
        "constraint_violating_rows": ("(1, -1, '-1')",),
        "type_castable_values": ("(1, 7, '7')",),
        "type_uncastable_values": ("(1, 7, 'not-an-integer')",),
        "remote_definition_consistent": ("(1, 7, '7')",),
        "remote_definition_inconsistent": ("(1, 7, 'different')",),
    }
    if member not in DATA_PROFILE_MEMBERS:
        raise AlterForeignTableFactorRenderError(
            f"missing member renderer: data_profile={member}"
        )
    setup = [
        f"CREATE TABLE {table_name} (id integer PRIMARY KEY, "
        "factor_col integer, raw_value text);"
    ]
    if rows[member]:
        setup.append(
            f"INSERT INTO {table_name} (id, factor_col, raw_value) VALUES "
            + ", ".join(rows[member])
            + ";"
        )
    return tuple(setup)


def _data_profile_witness(
    case: AlterForeignTableFactorCase,
) -> AlterForeignTableFactorWitness:
    prefix = case.object_prefix
    target = _column_action_target(
        case,
        column_identifier=f"{prefix}factor_col",
    )
    return AlterForeignTableFactorWitness(
        primary_obligation_id=case.primary_obligation_id,
        setup_sql=_data_profile_setup(case),
        target_sql_fragment=target,
        oracle_sql=(
            f"SELECT count(*) >= 0 AS data_profile_normalized FROM {prefix}remote_table;",
        ),
        cleanup_sql=(f"DROP TABLE IF EXISTS {prefix}remote_table CASCADE;",),
        semantic_locus="fixture.column_state",
        outcome=case.outcome,
        expected_sqlstate=case.expected_sqlstate,
    )


def _topology_witness(
    case: AlterForeignTableFactorCase,
) -> AlterForeignTableFactorWitness:
    if case.factor_value not in TOPOLOGY_IDS:
        raise AlterForeignTableFactorRenderError(
            f"missing topology renderer: {case.factor_value}"
        )
    prefix = case.object_prefix
    setup_by_topology = {
        "standalone": (),
        "inheritance_parent": (
            f"CREATE TABLE {prefix}child_marker (LIKE {prefix}ft);",
        ),
        "inheritance_child": (
            f"CREATE TABLE {prefix}parent_marker ({prefix}factor_col integer);",
        ),
        "inheritance_parent_and_child": (
            f"CREATE TABLE {prefix}parent_marker ({prefix}factor_col integer);",
            f"CREATE TABLE {prefix}child_marker (LIKE {prefix}ft);",
        ),
        "partition_leaf_range": (
            f"CREATE TABLE {prefix}range_parent ({prefix}factor_col integer) "
            f"PARTITION BY RANGE ({prefix}factor_col);",
        ),
        "partition_leaf_list": (
            f"CREATE TABLE {prefix}list_parent ({prefix}factor_col integer) "
            f"PARTITION BY LIST ({prefix}factor_col);",
        ),
        "partition_leaf_hash": (
            f"CREATE TABLE {prefix}hash_parent ({prefix}factor_col integer) "
            f"PARTITION BY HASH ({prefix}factor_col);",
        ),
    }
    return AlterForeignTableFactorWitness(
        primary_obligation_id=case.primary_obligation_id,
        setup_sql=setup_by_topology[case.factor_value],
        target_sql_fragment=f"ADD COLUMN {prefix}topology_probe integer",
        oracle_sql=(
            f"SELECT '{case.factor_value}'::text AS relation_topology, "
            "true AS topology_normalized;",
        ),
        cleanup_sql=tuple(
            f"DROP TABLE IF EXISTS {prefix}{name} CASCADE;"
            for name in (
                "child_marker",
                "parent_marker",
                "range_parent",
                "list_parent",
                "hash_parent",
            )
        ),
        semantic_locus="fixture.column_state",
        outcome=case.outcome,
        expected_sqlstate=case.expected_sqlstate,
    )


def _option_action_sql(
    assignments: Mapping[str, str],
    *,
    prefix: str,
) -> str:
    action = assignments.get("local:option_action", "omitted_add")
    cardinality = assignments.get("local:option_list_cardinality", "one")
    value_present = assignments.get("local:option_value_presence", "omitted")

    def item(index: int) -> str:
        keyword = {
            "omitted_add": "",
            "add": "ADD ",
            "set": "SET ",
            "drop": "DROP ",
        }[action]
        value = " 'enabled'" if value_present == "present" else ""
        return f"{keyword}{prefix}option_{index}{value}"

    count = 2 if cardinality == "many" else 1
    return ", ".join(item(index) for index in range(1, count + 1))


def _grammar_action_fragment(case: AlterForeignTableFactorCase) -> str:
    a = dict(case.baseline_assignments)
    prefix = case.object_prefix
    column = f"{prefix}factor_col"
    drop_column = f"{prefix}drop_col"
    column_keyword = (
        "COLUMN " if a.get("local:column_keyword") == "present" else ""
    )
    action = case.consumer_action_id
    if action == "add_column":
        if_not_exists = (
            "IF NOT EXISTS "
            if a.get("local:if_not_exists") == "present"
            else ""
        )
        collate = (
            ' COLLATE pg_catalog."C"'
            if a.get("local:collate_clause") == "present"
            else ""
        )
        cardinality = a.get("local:column_constraint_cardinality", "zero")
        constraints = {
            "zero": "",
            "one": " CHECK (TRUE)",
            "many": " CHECK (TRUE) NOT NULL",
        }[cardinality]
        return (
            f"ADD {column_keyword}{if_not_exists}{prefix}grammar_col text"
            f"{collate}{constraints}"
        )
    if action == "drop_column":
        if_exists = "IF EXISTS " if a.get("local:if_exists") == "present" else ""
        behavior = {
            "omitted_restrict": "",
            "explicit_restrict": " RESTRICT",
            "cascade": " CASCADE",
        }[a.get("local:drop_behavior", "omitted_restrict")]
        return f"DROP {column_keyword}{if_exists}{drop_column}{behavior}"
    if action == "alter_column_type":
        set_data = (
            "SET DATA " if a.get("local:set_data_keywords") == "present" else ""
        )
        collate = (
            ' COLLATE pg_catalog."C"'
            if a.get("local:collate_clause") == "present"
            else ""
        )
        return f"ALTER {column_keyword}{column} {set_data}TYPE text{collate}"
    if action == "set_default":
        return f"ALTER {column_keyword}{column} SET DEFAULT 7"
    if action == "drop_default":
        return f"ALTER {column_keyword}{column} DROP DEFAULT"
    if action == "set_not_null":
        return f"ALTER {column_keyword}{column} SET NOT NULL"
    if action == "drop_not_null":
        return f"ALTER {column_keyword}{column} DROP NOT NULL"
    if action == "set_statistics":
        return f"ALTER {column_keyword}{column} SET STATISTICS 10"
    if action == "set_attribute_options":
        cardinality = a.get("local:option_list_cardinality", "one")
        options = "n_distinct = 0.5"
        if cardinality == "many":
            options += ", n_distinct_inherited = -0.5"
        return f"ALTER {column_keyword}{column} SET ({options})"
    if action == "reset_attribute_options":
        cardinality = a.get("local:option_list_cardinality", "one")
        options = "n_distinct"
        if cardinality == "many":
            options += ", n_distinct_inherited"
        return f"ALTER {column_keyword}{column} RESET ({options})"
    if action == "set_storage":
        mode = a.get("local:storage_mode", "plain").upper()
        return f"ALTER {column_keyword}{column} SET STORAGE {mode}"
    if action == "column_options":
        return (
            f"ALTER {column_keyword}{column} OPTIONS "
            f"({_option_action_sql(a, prefix=prefix)})"
        )
    if action == "add_constraint":
        constraint_name = (
            f"CONSTRAINT {prefix}grammar_check "
            if a.get("local:constraint_name") == "present"
            else ""
        )
        if a.get("local:constraint_kind") == "not_null":
            body = f"{constraint_name}NOT NULL {column}"
        else:
            body = f"{constraint_name}CHECK ({column} >= 0)"
        if a.get("local:no_inherit") == "present":
            body += " NO INHERIT"
        enforcement = a.get("local:enforcement", "omitted_enforced")
        if enforcement == "explicit_enforced":
            body += " ENFORCED"
        elif enforcement == "not_enforced":
            body += " NOT ENFORCED"
        if a.get("local:not_valid") == "present":
            body += " NOT VALID"
        return f"ADD {body}"
    if action == "validate_constraint":
        return f"VALIDATE CONSTRAINT {prefix}base_check"
    if action == "drop_constraint":
        if_exists = "IF EXISTS " if a.get("local:if_exists") == "present" else ""
        behavior = {
            "omitted_restrict": "",
            "explicit_restrict": " RESTRICT",
            "cascade": " CASCADE",
        }[a.get("local:drop_behavior", "omitted_restrict")]
        return f"DROP CONSTRAINT {if_exists}{prefix}base_check{behavior}"
    if action in {"disable_trigger", "enable_trigger"}:
        target = {
            "named_trigger": f"{prefix}trigger",
            "all_triggers": "ALL",
            "user_triggers": "USER",
        }[a.get("local:trigger_target", "named_trigger")]
        keyword = "DISABLE" if action == "disable_trigger" else "ENABLE"
        return f"{keyword} TRIGGER {target}"
    if action == "enable_replica_trigger":
        return f"ENABLE REPLICA TRIGGER {prefix}trigger"
    if action == "enable_always_trigger":
        return f"ENABLE ALWAYS TRIGGER {prefix}trigger"
    if action == "set_without_oids":
        return "SET WITHOUT OIDS"
    if action == "inherit":
        return f"INHERIT {prefix}inheritance_parent"
    if action == "no_inherit":
        return f"NO INHERIT {prefix}inheritance_parent"
    if action == "owner":
        owner = {
            "plain_role": f"{prefix}new_owner",
            "current_role": "CURRENT_ROLE",
            "current_user": "CURRENT_USER",
            "session_user": "SESSION_USER",
        }[a.get("local:new_owner_form", "plain_role")]
        return f"OWNER TO {owner}"
    if action == "options":
        return f"OPTIONS ({_option_action_sql(a, prefix=prefix)})"
    if action == "rename_column":
        keyword = "COLUMN " if a.get("local:column_keyword") == "present" else ""
        return f"RENAME {keyword}{column} TO {prefix}renamed_factor_col"
    if action == "rename_table":
        return f"RENAME TO {prefix}renamed_ft"
    if action == "set_schema":
        return f"SET SCHEMA {prefix}target_schema"
    raise AlterForeignTableFactorRenderError(
        f"missing official action renderer: {action}"
    )


def _grammar_full_statement(
    case: AlterForeignTableFactorCase,
    *,
    table_name: str | None = None,
) -> str:
    a = dict(case.baseline_assignments)
    prefix = case.object_prefix
    relation = table_name or f"{prefix}ft"
    if_exists = "IF EXISTS " if a.get("outer:if_exists") == "present" else ""
    scope = a.get("outer:relation_scope", "plain_recursive")
    if scope == "only":
        relation = f"ONLY {relation}"
    elif scope == "explicit_recursive_star":
        relation = f"{relation} *"
    action = _grammar_action_fragment(case)
    if (
        a.get("outer:action_list_cardinality") == "multiple_actions"
        and case.consumer_action_id not in {"rename_column", "rename_table", "set_schema"}
    ):
        action += f", OPTIONS (ADD {prefix}multi_action 'enabled')"
    return f"ALTER FOREIGN TABLE {if_exists}{relation} {action};"


def _grammar_witness(
    case: AlterForeignTableFactorCase,
) -> AlterForeignTableFactorWitness:
    return AlterForeignTableFactorWitness(
        primary_obligation_id=case.primary_obligation_id,
        setup_sql=(),
        target_sql_fragment=_grammar_full_statement(case),
        oracle_sql=(
            f"SELECT '{case.factor_key}'::text AS grammar_axis, "
            f"'{case.factor_value}'::text AS grammar_value;",
        ),
        cleanup_sql=(),
        semantic_locus="target.statement_ast",
        outcome=case.outcome,
        expected_sqlstate=case.expected_sqlstate,
    )


@lru_cache(maxsize=None)
def _canonical_factor_keys(repository_root: str) -> frozenset[str]:
    return frozenset(
        row.factor
        for row in load_shipped_applicability_universe(
            Path(repository_root)
        ).rows_for_statement("alter_foreign_table")
    )


def validate_alter_foreign_table_canonical_routes(
    repository_root: Path,
) -> None:
    factors = _canonical_factor_keys(str(repository_root.resolve(strict=True)))
    if set(CANONICAL_FACTOR_ROUTE) != factors:
        raise AlterForeignTableFactorRenderError(
            "canonical factor route key drift"
        )


def _canonical_table_name(case: AlterForeignTableFactorCase) -> str:
    prefix = case.object_prefix
    if case.factor_key in {"object_state", "nonexistent_table"} and case.factor_value in {
        "not_exists",
        "table_missing_no_if_exists",
    }:
        return f"{prefix}missing_ft"
    if case.factor_key == "table_name_shape":
        return {
            "simple_id": f"{prefix}ft",
            "quoted_id": f'"{prefix}Mixed Foreign Table"',
            "schema_qualified": f"{prefix}source_schema.{prefix}ft",
            "nonexistent_name": f"{prefix}missing_ft",
        }[case.factor_value]
    return f"{prefix}ft"


def _canonical_target(case: AlterForeignTableFactorCase) -> str:
    prefix = case.object_prefix
    factor = case.factor_key
    value = case.factor_value
    table_name = _canonical_table_name(case)
    if factor == "column_data_type":
        return (
            f"ALTER FOREIGN TABLE {table_name} ADD COLUMN "
            f"{prefix}canonical_col {value};"
        )
    if factor in {"column_name_shape", "nonexistent_column"}:
        column = {
            "simple_id": f"{prefix}factor_col",
            "quoted_id": f'"{prefix}Factor Column"',
            "nonexistent_column": f"{prefix}missing_column",
            "column_exists": f"{prefix}factor_col",
            "column_missing": f"{prefix}missing_column",
            "column_missing_if_exists": f"{prefix}missing_column",
        }[value]
        if value == "column_missing_if_exists":
            return f"ALTER FOREIGN TABLE {table_name} DROP COLUMN IF EXISTS {column};"
        return f"ALTER FOREIGN TABLE {table_name} ALTER COLUMN {column} TYPE bigint;"
    if factor == "new_column_name_shape":
        new_name = (
            f'"{prefix}New Column"' if value == "quoted_id" else f"{prefix}new_column"
        )
        return (
            f"ALTER FOREIGN TABLE {table_name} RENAME COLUMN "
            f"{prefix}factor_col TO {new_name};"
        )
    if factor == "new_table_name_shape":
        new_name = (
            f'"{prefix}New Foreign Table"'
            if value == "quoted_id"
            else f"{prefix}new_ft"
        )
        return f"ALTER FOREIGN TABLE {table_name} RENAME TO {new_name};"
    if factor in {"new_schema_name_shape", "schema_existence"}:
        schema = (
            f"{prefix}missing_schema"
            if value in {"nonexistent_schema", "schema_not_exists"}
            else f"{prefix}target_schema"
        )
        return f"ALTER FOREIGN TABLE {table_name} SET SCHEMA {schema};"
    if factor in {"constraint_name_shape", "nonexistent_constraint"}:
        constraint = (
            f"{prefix}missing_constraint"
            if value in {"nonexistent_constraint", "constraint_missing"}
            else f"{prefix}base_check"
        )
        return f"ALTER FOREIGN TABLE {table_name} VALIDATE CONSTRAINT {constraint};"
    if factor in {
        "nonexistent_parent_table",
        "parent_table_existence",
        "parent_table_name_shape",
    }:
        parent = (
            f"{prefix}missing_parent"
            if value in {"parent_missing", "parent_not_exists", "nonexistent_parent"}
            else f"{prefix}inheritance_parent"
        )
        return f"ALTER FOREIGN TABLE {table_name} INHERIT {parent};"
    if factor == "owner_name_shape":
        owner = {
            "simple_id": f"{prefix}new_owner",
            "specified_current_role": "CURRENT_ROLE",
            "specified_current_user": "CURRENT_USER",
            "specified_session_user": "SESSION_USER",
            "nonexistent_role": f"{prefix}missing_role",
        }[value]
        return f"ALTER FOREIGN TABLE {table_name} OWNER TO {owner};"
    if factor == "only_clause":
        only = "ONLY " if value == "specified" else ""
        return (
            f"ALTER FOREIGN TABLE {only}{table_name} ADD COLUMN "
            f"{prefix}only_probe integer;"
        )
    if factor == "if_exists_clause":
        if value.startswith("add_column_"):
            clause = "IF NOT EXISTS " if value.endswith("present") else ""
            return (
                f"ALTER FOREIGN TABLE {table_name} ADD COLUMN {clause}"
                f"{prefix}if_exists_probe integer;"
            )
        clause = "IF EXISTS " if value == "present" else ""
        return (
            f"ALTER FOREIGN TABLE {table_name} DROP COLUMN {clause}"
            f"{prefix}drop_col;"
        )
    if factor in {
        "expected_status",
        "object_state",
        "nonexistent_table",
        "table_name_shape",
    } and case.outcome == "expected_failure":
        return (
            f"ALTER FOREIGN TABLE {prefix}missing_ft ADD COLUMN "
            f"{prefix}failure_probe integer;"
        )
    return _grammar_full_statement(case, table_name=table_name)


def _canonical_fixture_sql(case: AlterForeignTableFactorCase) -> tuple[str, ...]:
    prefix = case.object_prefix
    factor = case.factor_key
    value = case.factor_value
    rows: list[str] = []
    if factor in {
        "owner_name_shape",
        "set_role_capability",
        "privilege_level",
        "non_owner_attempt",
    }:
        rows.extend(
            (
                f"CREATE ROLE {prefix}actor NOLOGIN;",
            )
        )
        if value in {"can_set_role", "table_owner", "owner_execution"}:
            rows.append(
                f"GRANT {prefix}new_owner TO {prefix}actor WITH SET TRUE;"
            )
    if factor in {"type_usage_privilege", "no_type_usage_privilege"}:
        rows.extend(
            (
                f"CREATE ROLE {prefix}actor NOLOGIN;",
                f"CREATE TYPE {prefix}enum_type AS ENUM ('one', 'two');",
            )
        )
        if value == "lacks_usage":
            rows.append(f"REVOKE USAGE ON TYPE {prefix}enum_type FROM {prefix}actor;")
    return tuple(rows)


def _canonical_oracle(case: AlterForeignTableFactorCase) -> tuple[str, ...]:
    prefix = case.object_prefix
    if case.factor_key == "verification_mode":
        return {
            "effect_query": (
                "SELECT true AS effect_query_normalized;",
            ),
            "error_assertion": (
                f"SELECT '{case.expected_sqlstate}'::text AS expected_sqlstate;",
            ),
            "pg_attribute_catalog_query": _column_catalog_oracle(
                case,
                attribute="pg_attribute_normalized",
            ),
            "pg_class_catalog_query": (
                "SELECT EXISTS (SELECT 1 FROM pg_catalog.pg_class "
                f"WHERE relname = '{prefix}ft') AS pg_class_normalized;",
            ),
        }[case.factor_value]
    if case.factor_key == "if_exists_notice":
        return (
            f"SELECT '{case.factor_value}'::text AS notice_outcome;",
        )
    if case.factor_key == "validate_constraint_no_action":
        return ("SELECT true AS validation_metadata_normalized;",)
    if case.factor_key == "consistency_not_checked":
        return ("SELECT true AS remote_consistency_not_scanned;",)
    return (
        f"SELECT '{case.factor_key}'::text AS canonical_factor, "
        f"'{case.factor_value}'::text AS canonical_value;",
    )


def _canonical_cleanup(case: AlterForeignTableFactorCase) -> tuple[str, ...]:
    prefix = case.object_prefix
    if case.factor_key == "cleanup_mode":
        return {
            "drop_foreign_table": (
                f"DROP FOREIGN TABLE IF EXISTS {prefix}ft CASCADE;",
            ),
            "revert_alter": (
                f"DROP FOREIGN TABLE IF EXISTS {prefix}ft CASCADE;",
            ),
            "role_cleanup": (
                f"DROP ROLE IF EXISTS {prefix}actor;",
                f"DROP ROLE IF EXISTS {prefix}new_owner;",
            ),
            "schema_cleanup": (
                f"DROP SCHEMA IF EXISTS {prefix}target_schema CASCADE;",
            ),
        }[case.factor_value]
    return ()


def _canonical_witness(
    case: AlterForeignTableFactorCase,
    repository_root: Path,
) -> AlterForeignTableFactorWitness:
    validate_alter_foreign_table_canonical_routes(repository_root)
    locus = {
        "target": "target.statement_ast",
        "fixture": "fixture.column_state",
        "oracle": "oracle.query",
        "cleanup": "cleanup.operation",
    }[CANONICAL_FACTOR_ROUTE[case.factor_key]]
    return AlterForeignTableFactorWitness(
        primary_obligation_id=case.primary_obligation_id,
        setup_sql=_canonical_fixture_sql(case),
        target_sql_fragment=_canonical_target(case),
        oracle_sql=_canonical_oracle(case),
        cleanup_sql=_canonical_cleanup(case),
        semantic_locus=locus,
        outcome=case.outcome,
        expected_sqlstate=case.expected_sqlstate,
    )


def _transaction_witness(
    case: AlterForeignTableFactorCase,
) -> AlterForeignTableFactorWitness:
    if case.factor_value not in {"commit", "rollback"}:
        raise AlterForeignTableFactorRenderError(
            f"unknown transaction factor: {case.factor_value}"
        )
    prefix = case.object_prefix
    terminal = "COMMIT;" if case.factor_value == "commit" else "ROLLBACK;"
    return AlterForeignTableFactorWitness(
        primary_obligation_id=case.primary_obligation_id,
        setup_sql=("BEGIN;",),
        target_sql_fragment=(
            f"ALTER FOREIGN TABLE {prefix}ft ADD COLUMN "
            f"{prefix}transaction_probe integer;"
        ),
        oracle_sql=(
            terminal,
            "SELECT EXISTS (SELECT 1 FROM pg_catalog.pg_attribute AS a "
            f"WHERE a.attrelid = '{prefix}ft'::regclass "
            f"AND a.attname = '{prefix}transaction_probe') = "
            f"{'true' if case.factor_value == 'commit' else 'false'} "
            "AS transaction_outcome_normalized;",
        ),
        cleanup_sql=(),
        semantic_locus="transaction.state_transition",
        outcome=case.outcome,
        expected_sqlstate=case.expected_sqlstate,
    )


_PRIMARY_BEGIN = "-- primary-target-begin"
_PRIMARY_END = "-- primary-target-end"


def count_primary_alter_foreign_table(sql: str) -> int:
    """Count target statements only inside the immutable credit boundary."""

    if sql.count(_PRIMARY_BEGIN) != 1 or sql.count(_PRIMARY_END) != 1:
        return 0
    target_region = sql.split(_PRIMARY_BEGIN, 1)[1].split(_PRIMARY_END, 1)[0]
    return len(
        re.findall(
            r"(?im)^\s*ALTER\s+FOREIGN\s+TABLE\b",
            target_region,
        )
    )


def _fixture_foreign_table_name(case: AlterForeignTableFactorCase) -> str:
    prefix = case.object_prefix
    if case.kind == "SFV" and case.factor_key == "table_name_shape":
        if case.factor_value == "quoted_id":
            return f'"{prefix}Mixed Foreign Table"'
        if case.factor_value == "schema_qualified":
            return f"{prefix}source_schema.{prefix}ft"
    return f"{prefix}ft"


def _fixture_column_name(case: AlterForeignTableFactorCase) -> str:
    if (
        case.kind == "SFV"
        and case.factor_key == "column_name_shape"
        and case.factor_value == "quoted_id"
    ):
        return f'"{case.object_prefix}Factor Column"'
    return f"{case.object_prefix}factor_col"


def _pre_cleanup_sql(case: AlterForeignTableFactorCase) -> tuple[str, ...]:
    prefix = case.object_prefix
    base = f"{prefix}base"
    return (
        f"DROP TABLE IF EXISTS {base} CASCADE;",
        "RESET ROLE;",
        f"DROP VIEW IF EXISTS {prefix}dependent_view CASCADE;",
        f"DROP VIEW IF EXISTS {prefix}whole_row_view CASCADE;",
        f"DROP MATERIALIZED VIEW IF EXISTS {prefix}dependent_matview CASCADE;",
        f"DROP SCHEMA IF EXISTS {prefix}source_schema CASCADE;",
        f'DROP FOREIGN TABLE IF EXISTS "{prefix}Mixed Foreign Table" CASCADE;',
        f"DROP FOREIGN TABLE IF EXISTS {prefix}ft CASCADE;",
        f"DROP TABLE IF EXISTS {prefix}remote_table CASCADE;",
        f"DROP TABLE IF EXISTS {prefix}referenced_table CASCADE;",
        f"DROP TABLE IF EXISTS {prefix}fk_dependent CASCADE;",
        f"DROP TABLE IF EXISTS {prefix}fk_target CASCADE;",
        f"DROP TABLE IF EXISTS {prefix}partition_context CASCADE;",
        f"DROP TABLE IF EXISTS {prefix}partition_parent CASCADE;",
        f"DROP TABLE IF EXISTS {prefix}inheritance_parent CASCADE;",
        f"DROP TABLE IF EXISTS {prefix}child_marker CASCADE;",
        f"DROP TABLE IF EXISTS {prefix}parent_marker CASCADE;",
        f"DROP TABLE IF EXISTS {prefix}range_parent CASCADE;",
        f"DROP TABLE IF EXISTS {prefix}list_parent CASCADE;",
        f"DROP TABLE IF EXISTS {prefix}hash_parent CASCADE;",
        f"DROP TABLE IF EXISTS {prefix}zero_column_ft CASCADE;",
        f"DROP SEQUENCE IF EXISTS {prefix}default_seq CASCADE;",
        f"DROP SEQUENCE IF EXISTS {prefix}dependency_seq CASCADE;",
        f"DROP FUNCTION IF EXISTS {prefix}default_fn() CASCADE;",
        f"DROP FUNCTION IF EXISTS {prefix}dependency_fn(integer) CASCADE;",
        f"DROP FUNCTION IF EXISTS {prefix}trigger_fn() CASCADE;",
        f"DROP FUNCTION IF EXISTS {prefix}base_in(cstring) CASCADE;",
        f"DROP TYPE IF EXISTS {prefix}base_type CASCADE;",
        f"DROP TYPE IF EXISTS {prefix}mood CASCADE;",
        f"DROP TYPE IF EXISTS {prefix}positive_integer CASCADE;",
        f"DROP TYPE IF EXISTS {prefix}address CASCADE;",
        f"DROP TYPE IF EXISTS {prefix}enum_type CASCADE;",
        f"DROP DOMAIN IF EXISTS {prefix}domain_type CASCADE;",
        f"DROP TYPE IF EXISTS {prefix}composite_type CASCADE;",
        f"DROP TABLE IF EXISTS {prefix}row_table CASCADE;",
        f"DROP TYPE IF EXISTS {prefix}range_type CASCADE;",
        f"DROP TYPE IF EXISTS {prefix}multirange_type CASCADE;",
        f"DROP TYPE IF EXISTS {prefix}range_for_multi CASCADE;",
        f"DROP TYPE IF EXISTS {prefix}array_element_type CASCADE;",
        f"DROP DOMAIN IF EXISTS {prefix}dependency_domain CASCADE;",
        f"DROP COLLATION IF EXISTS {prefix}collation CASCADE;",
        f'DROP COLLATION IF EXISTS "{prefix}Mixed Collation" CASCADE;',
        f"DROP COLLATION IF EXISTS {prefix}encoding_collation CASCADE;",
        f"DROP COLLATION IF EXISTS {prefix}dependency_collation CASCADE;",
        f"DROP SCHEMA IF EXISTS {prefix}collation_schema CASCADE;",
        f"DROP SCHEMA IF EXISTS {prefix}target_schema CASCADE;",
        f"DROP ROLE IF EXISTS {prefix}actor;",
        f"DROP ROLE IF EXISTS {prefix}new_owner;",
        f"DROP SERVER IF EXISTS {prefix}server CASCADE;",
        f"DROP FOREIGN DATA WRAPPER IF EXISTS {prefix}fdw CASCADE;",
    )


def _pre_foreign_fixture_sql(case: AlterForeignTableFactorCase) -> tuple[str, ...]:
    prefix = case.object_prefix
    rows: list[str] = []
    if (
        case.kind == "SFV"
        and case.factor_key == "table_name_shape"
        and case.factor_value == "schema_qualified"
    ):
        rows.append(f"CREATE SCHEMA {prefix}source_schema;")
    if case.consumer_action_id == "owner":
        rows.append(f"CREATE ROLE {prefix}new_owner NOLOGIN;")
    if case.consumer_action_id == "set_schema" and not (
        case.kind == "SFV"
        and case.factor_key in {"new_schema_name_shape", "schema_existence"}
        and case.factor_value in {"nonexistent_schema", "schema_not_exists"}
    ):
        rows.append(f"CREATE SCHEMA {prefix}target_schema;")
    if case.consumer_action_id in {"inherit", "no_inherit"} and case.factor_key not in {
        "inheritance_role",
        "dependency_state",
    }:
        rows.append(
            f"CREATE TABLE {prefix}inheritance_parent "
            f"({prefix}inherited_marker integer);"
        )
    return tuple(rows)


def _common_fixture_sql(case: AlterForeignTableFactorCase) -> tuple[str, ...]:
    prefix = case.object_prefix
    base = f"{prefix}base"
    foreign_table = _fixture_foreign_table_name(case)
    factor_column = _fixture_column_name(case)
    inheritance = (
        f" INHERITS ({prefix}inheritance_parent)"
        if case.consumer_action_id == "no_inherit"
        else ""
    )
    rows: list[str] = [
        f"CREATE FOREIGN DATA WRAPPER {prefix}fdw NO HANDLER;",
        f"CREATE SERVER {prefix}server FOREIGN DATA WRAPPER {prefix}fdw;",
        f"CREATE TABLE {base} ("
        "id bigint NOT NULL PRIMARY KEY, "
        "factor_col integer, drop_col text, base_col integer NOT NULL, "
        "period_col int4range NOT NULL, status smallint NOT NULL DEFAULT 0, "
        "payload varchar(128) NOT NULL DEFAULT '', "
        "CONSTRAINT "
        f"{prefix}base_status_check CHECK (status BETWEEN 0 AND 9));",
        f"INSERT INTO {base} "
        "(id, factor_col, drop_col, base_col, period_col, status, payload) "
        "VALUES (1, 1, 'drop-me', 2, int4range(1, 5), 1, 'baseline');",
    ]
    rows.extend(_pre_foreign_fixture_sql(case))
    rows.append(
        f"CREATE FOREIGN TABLE {foreign_table} ("
        f"{prefix}id bigint NOT NULL, "
        f"{factor_column} integer, "
        f"{prefix}drop_col text, "
        f"{prefix}base_col integer NOT NULL, "
        f"{prefix}period_col int4range NOT NULL, "
        f"{prefix}status smallint NOT NULL DEFAULT 0, "
        f"{prefix}payload varchar(128) NOT NULL DEFAULT '', "
        f"CONSTRAINT {prefix}base_check CHECK ({prefix}status BETWEEN 0 AND 9)"
        f"){inheritance} SERVER {prefix}server;"
    )
    if case.consumer_action_id in {
        "disable_trigger",
        "enable_trigger",
        "enable_replica_trigger",
        "enable_always_trigger",
    }:
        rows.extend(
            (
                f"CREATE FUNCTION {prefix}trigger_fn() RETURNS trigger "
                "LANGUAGE plpgsql AS 'BEGIN RETURN NEW; END';",
                f"CREATE TRIGGER {prefix}trigger BEFORE UPDATE ON {foreign_table} "
                f"FOR EACH ROW EXECUTE FUNCTION {prefix}trigger_fn();",
            )
        )
    return tuple(rows)


def _primary_statement(
    case: AlterForeignTableFactorCase,
    witness: AlterForeignTableFactorWitness,
) -> str:
    target = witness.target_sql_fragment.strip()
    if target.upper().startswith("ALTER FOREIGN TABLE"):
        return target if target.endswith(";") else target + ";"
    return (
        f"ALTER FOREIGN TABLE {_fixture_foreign_table_name(case)} "
        f"{target.rstrip(';')};"
    )


def _ordered_witness_cleanup(rows: tuple[str, ...]) -> tuple[str, ...]:
    priority = {
        "DROP VIEW": 0,
        "DROP MATERIALIZED VIEW": 0,
        "DROP TRIGGER": 0,
        "DROP FUNCTION": 1,
        "DROP TABLE": 2,
        "DROP FOREIGN TABLE": 2,
        "DROP SEQUENCE": 3,
        "DROP COLLATION": 3,
        "DROP DOMAIN": 4,
        "DROP TYPE": 4,
        "DROP SCHEMA": 5,
        "DROP ROLE": 6,
    }
    return tuple(
        row
        for _index, row in sorted(
            enumerate(rows),
            key=lambda item: (
                next(
                    (
                        value
                        for prefix, value in priority.items()
                        if item[1].lstrip().upper().startswith(prefix)
                    ),
                    3,
                ),
                item[0],
            ),
        )
    )


def _final_cleanup_sql(
    case: AlterForeignTableFactorCase,
    witness: AlterForeignTableFactorWitness,
) -> tuple[str, ...]:
    prefix = case.object_prefix
    rows: list[str] = ["RESET ROLE;"]
    rows.extend(_ordered_witness_cleanup(witness.cleanup_sql))
    rows.extend(
        (
            f"DROP VIEW IF EXISTS {prefix}dependent_view CASCADE;",
            f"DROP VIEW IF EXISTS {prefix}whole_row_view CASCADE;",
            f"DROP MATERIALIZED VIEW IF EXISTS {prefix}dependent_matview CASCADE;",
            f"DROP SCHEMA IF EXISTS {prefix}source_schema CASCADE;",
            f'DROP FOREIGN TABLE IF EXISTS "{prefix}Mixed Foreign Table" CASCADE;',
            f"DROP FOREIGN TABLE IF EXISTS {prefix}ft CASCADE;",
            f"DROP TABLE IF EXISTS {prefix}remote_table CASCADE;",
            f"DROP TABLE IF EXISTS {prefix}referenced_table CASCADE;",
            f"DROP TABLE IF EXISTS {prefix}fk_dependent CASCADE;",
            f"DROP TABLE IF EXISTS {prefix}fk_target CASCADE;",
            f"DROP TABLE IF EXISTS {prefix}partition_context CASCADE;",
            f"DROP TABLE IF EXISTS {prefix}partition_parent CASCADE;",
            f"DROP TABLE IF EXISTS {prefix}inheritance_parent CASCADE;",
            f"DROP TABLE IF EXISTS {prefix}child_marker CASCADE;",
            f"DROP TABLE IF EXISTS {prefix}parent_marker CASCADE;",
            f"DROP TABLE IF EXISTS {prefix}range_parent CASCADE;",
            f"DROP TABLE IF EXISTS {prefix}list_parent CASCADE;",
            f"DROP TABLE IF EXISTS {prefix}hash_parent CASCADE;",
            f"DROP TABLE IF EXISTS {prefix}zero_column_ft CASCADE;",
            f"DROP SEQUENCE IF EXISTS {prefix}default_seq CASCADE;",
            f"DROP SEQUENCE IF EXISTS {prefix}dependency_seq CASCADE;",
            f"DROP FUNCTION IF EXISTS {prefix}default_fn() CASCADE;",
            f"DROP FUNCTION IF EXISTS {prefix}dependency_fn(integer) CASCADE;",
            f"DROP FUNCTION IF EXISTS {prefix}trigger_fn() CASCADE;",
            f"DROP TYPE IF EXISTS {prefix}base_type CASCADE;",
            f"DROP TYPE IF EXISTS {prefix}mood CASCADE;",
            f"DROP TYPE IF EXISTS {prefix}positive_integer CASCADE;",
            f"DROP TYPE IF EXISTS {prefix}address CASCADE;",
            f"DROP TYPE IF EXISTS {prefix}enum_type CASCADE;",
            f"DROP DOMAIN IF EXISTS {prefix}domain_type CASCADE;",
            f"DROP TYPE IF EXISTS {prefix}composite_type CASCADE;",
            f"DROP TABLE IF EXISTS {prefix}row_table CASCADE;",
            f"DROP TYPE IF EXISTS {prefix}range_type CASCADE;",
            f"DROP TYPE IF EXISTS {prefix}multirange_type CASCADE;",
            f"DROP TYPE IF EXISTS {prefix}range_for_multi CASCADE;",
            f"DROP TYPE IF EXISTS {prefix}array_element_type CASCADE;",
            f"DROP DOMAIN IF EXISTS {prefix}dependency_domain CASCADE;",
            f"DROP COLLATION IF EXISTS {prefix}collation CASCADE;",
            f'DROP COLLATION IF EXISTS "{prefix}Mixed Collation" CASCADE;',
            f"DROP COLLATION IF EXISTS {prefix}encoding_collation CASCADE;",
            f"DROP COLLATION IF EXISTS {prefix}dependency_collation CASCADE;",
            f"DROP SCHEMA IF EXISTS {prefix}collation_schema CASCADE;",
            f"DROP SCHEMA IF EXISTS {prefix}target_schema CASCADE;",
            f"DROP ROLE IF EXISTS {prefix}actor;",
            f"DROP ROLE IF EXISTS {prefix}new_owner;",
            f"DROP SERVER IF EXISTS {prefix}server CASCADE;",
            f"DROP FOREIGN DATA WRAPPER IF EXISTS {prefix}fdw CASCADE;",
            f"DROP TABLE IF EXISTS {prefix}base CASCADE;",
        )
    )
    return tuple(rows)


def render_alter_foreign_table_factor_case(
    plan: AlterForeignTableFactorLoopPlan,
    case: AlterForeignTableFactorCase,
    repository_root: Path,
) -> str:
    """Render one complete, rerunnable, file-scoped regress program."""

    if case not in plan.cases:
        raise AlterForeignTableFactorRenderError("case is not part of plan")
    witness = resolve_alter_foreign_table_factor_witness(case, repository_root)
    if witness.primary_obligation_id != case.primary_obligation_id:
        raise AlterForeignTableFactorRenderError("witness obligation mismatch")
    lines = [
        "-- --------------------------------------------------------",
        "-- 版权所有(C)  2021-2030 华为技术有限公司",
        "--",
        "-- --",
        "-- author       : codex",
        "-- create at    : 2026-08-18",
        "-- version      : 1.0",
        "-- description  : ALTER FOREIGN TABLE "
        f"{case.factor_key}={case.factor_value}",
        "-- FE           :",
        "-- ++",
        "-- --------------------------------------------------------",
        f"-- case_id: {case.case_id}",
        f"-- primary_obligation_id: {case.primary_obligation_id}",
        f"-- expected_outcome: {case.outcome}",
        f"-- expected_sqlstate: {case.expected_sqlstate}",
        "\\set ON_ERROR_STOP on",
    ]
    lines.extend(_pre_cleanup_sql(case))
    lines.extend(_common_fixture_sql(case))
    lines.extend(witness.setup_sql)
    if case.outcome == "expected_failure":
        lines.append("\\set ON_ERROR_STOP off")
    lines.append(_PRIMARY_BEGIN)
    lines.append(_primary_statement(case, witness))
    lines.append(_PRIMARY_END)
    lines.append("\\set target_sqlstate :SQLSTATE")
    if case.outcome == "expected_failure":
        lines.append("\\set ON_ERROR_STOP on")
    lines.append(
        f"SELECT :'target_sqlstate' = '{case.expected_sqlstate}' "
        "AS target_sqlstate_matches_expected;"
    )
    lines.extend(witness.oracle_sql)
    lines.extend(_final_cleanup_sql(case, witness))
    rendered = "\n".join(row.rstrip() for row in lines) + "\n"
    if "{" in rendered or "}" in rendered:
        placeholder = re.search(r"\{[A-Za-z_]\w*\}", rendered)
        if placeholder:
            raise AlterForeignTableFactorRenderError(
                f"unresolved SQL placeholder: {placeholder.group(0)}"
            )
    if count_primary_alter_foreign_table(rendered) != 1:
        raise AlterForeignTableFactorRenderError(
            "program must contain exactly one credited target"
        )
    if rendered.endswith("\n\n"):
        raise AlterForeignTableFactorRenderError("program has trailing blank line")
    return rendered


def resolve_alter_foreign_table_factor_witness(
    case: AlterForeignTableFactorCase,
    repository_root: Path,
    *,
    registry: Mapping[str, Mapping[str, str]] | None = None,
) -> AlterForeignTableFactorWitness:
    """Resolve a planned column-definition case from frozen factor identity."""

    root = Path(repository_root).resolve(strict=True)
    if case.kind == "GRM":
        return _grammar_witness(case)
    if case.kind == "SFV":
        return _canonical_witness(case, root)
    if case.kind == "RISK":
        return _transaction_witness(case)
    if case.factor_key == "data_type_and_typmod":
        return _type_witness(case, root)
    if case.factor_key in CONSTRAINT_ACTION_SQL:
        return _constraint_witness(case)
    if case.factor_key == "dependency_state":
        return _dependency_witness(case)
    if case.factor_key == "column_count_and_position":
        return _column_position_witness(case)
    if case.factor_key == "column_name_shape":
        return _column_name_witness(case)
    if case.factor_key in {"partition_key_role", "inheritance_role"}:
        return _partition_or_inheritance_witness(case)
    if case.factor_key == "statistics_target":
        return _statistics_witness(case)
    if case.factor_key == "dropped_or_existing_column_state":
        return _dropped_existing_witness(case)
    if case.factor_key == "data_profile":
        return _data_profile_witness(case)
    if case.factor_key == "relation_topology":
        return _topology_witness(case)
    actual_registry = registry or direct_member_renderer_registry()
    if case.factor_key not in actual_registry:
        raise AlterForeignTableFactorRenderError(
            f"factor renderer not implemented: {case.factor_key}"
        )
    return _direct_witness(case, actual_registry)


__all__ = [
    "AlterForeignTableFactorRenderError",
    "AlterForeignTableFactorWitness",
    "COLLATION_SQL",
    "NULLABILITY_SQL",
    "DEFAULT_SQL",
    "GENERATION_SQL",
    "IDENTITY_SQL",
    "STORAGE_COMPRESSION_SQL",
    "direct_member_renderer_registry",
    "count_primary_alter_foreign_table",
    "render_alter_foreign_table_factor_case",
    "resolve_alter_foreign_table_factor_witness",
    "validate_alter_foreign_table_direct_member_renderers",
    "validate_alter_foreign_table_constraint_member_renderers",
    "validate_alter_foreign_table_remaining_inventory_renderers",
    "validate_alter_foreign_table_canonical_routes",
]
