-- object_key: table_01_comprehensive_types
-- aliases: normal table comprehensive types, broad built-in column types
-- object_kind: table
-- compatibility_target: postgresql-18.4
-- purpose: reusable normal-table base object spanning PostgreSQL built-in column families
-- primary_object: tab_normal_comprehensive

DROP TABLE IF EXISTS tab_normal_comprehensive;

CREATE TABLE tab_normal_comprehensive
(
    id_col                    integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    smallint_col              smallint,
    integer_col               integer,
    bigint_col                bigint,
    numeric_col               numeric(16, 4),
    real_col                  real,
    double_col                double precision,
    money_col                 money,
    char_col                  char(20),
    character_col             character(20),
    varchar_col               varchar(100),
    character_varying_col     character varying(100),
    text_col                  text,
    bpchar_col                bpchar(20),
    boolean_col               boolean,
    bytea_col                 bytea,
    date_col                  date,
    time_col                  time,
    timetz_col                timetz,
    timestamp_col             timestamp,
    timestamptz_col           timestamptz,
    interval_col              interval,
    inet_col                  inet,
    cidr_col                  cidr,
    macaddr_col               macaddr,
    macaddr8_col              macaddr8,
    bit_col                   bit(8),
    varbit_col                varbit(32),
    tsvector_col              tsvector,
    tsquery_col               tsquery,
    json_col                  json,
    jsonb_col                 jsonb,
    jsonpath_col              jsonpath,
    uuid_col                  uuid,
    xml_col                   xml,
    point_col                 point,
    line_col                  line,
    lseg_col                  lseg,
    box_col                   box,
    path_col                  path,
    polygon_col               polygon,
    circle_col                circle,
    int4range_col             int4range,
    int8range_col             int8range,
    numrange_col              numrange,
    tsrange_col               tsrange,
    tstzrange_col             tstzrange,
    daterange_col             daterange,
    int4multirange_col        int4multirange,
    int8multirange_col        int8multirange,
    nummultirange_col         nummultirange,
    tsmultirange_col          tsmultirange,
    tstzmultirange_col        tstzmultirange,
    datemultirange_col        datemultirange,
    int_array_col             integer[],
    text_array_col            text[],
    varchar_array_col         varchar[],
    pg_lsn_col                pg_lsn,
    pg_snapshot_col           pg_snapshot,
    oid_col                   oid,
    tid_col                   tid,
    xid_col                   xid,
    xid8_col                  xid8,
    cid_col                   cid,
    name_col                  name,
    regclass_col              regclass,
    regtype_col               regtype,
    regrole_col               regrole,
    regnamespace_col          regnamespace
);
